info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
  liquibase:
    url: jdbc:postgresql://localhost:15432/postgres
  cloud:
    gcp:
      project-id: ras-rm-dev
      pubsub:
        emulator-host: localhost:18681

survey-svc:
  connection-config:
    username: admin
    password: secret
    retry-attempts: 5

case-distribution:
  retrieval-max: 50
  delay-milli-seconds: 500

schedules:
  validation-schedule-delay-milli-seconds: 1000
  distribution-schedule-delay-milli-seconds: 1000

collection-instrument-svc:
    connection-config:
        port: 18002

party-svc:
    connection-config:
        port: 18002

internet-access-code-svc:
  iac-post-path: /iacs
  iac-put-path: /iacs/{iac}
  connection-config:
    scheme: http
    host: localhost
    port: 18002
    username: admin
    password: secret

collection-exercise-svc:
  connection-config:
    port: 38145
    username: admin
    password: secret

gcp:
  project: "ras-rm-dev"
  receiptSubscription: "test_subscription"
  caseNotificationTopic: "test_topic"
  caseNotificationSubscription: "test_case_creation_subscription"
