info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: ERROR
    org.springframework: ERROR
  profile: CLOUD
  useJson: true

liquibase:
  user: ${cloud.services.postgresql.connection.username}
  password: ${cloud.services.postgresql.connection.password}
  default-schema: casesvc
  url: ${cloud.services.postgresql.connection.jdbcurl}
  changeLog: classpath:/database/changelog-master.yml

security:
  basic:
    enabled: true
    realm: sdc
  user:
    name: admin
    password: secret

management:
  security:
    roles: SUPERUSER
    enabled: true
  health:
    rabbit:
      enabled: false

server:
  port: 8171
  servlet-path: /

spring:
  application:
    name: ONS CaseService
  datasource:
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
    continue-on-error: true
    schema: classpath:/schema-cloud.sql
    user: ${cloud.services.postgresql.connection.username}
    password: ${cloud.services.postgresql.connection.password}
    default-schema: casesvc
    url: ${cloud.services.postgresql.connection.jdbcurl}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update
        default_schema: casesvc

data-grid:
  address: ${cloud.services.redis.connection.host}:${cloud.services.redis.connection.port}
  list-time-to-live-seconds: 600
  list-time-to-wait-seconds: 600
  report-lock-time-to-live-seconds: 300

internet-access-code-svc:
  iac-post-path: /iacs
  iac-put-path: /iacs/{iac}
  connection-config:
    scheme: http
    host: iacsvc.apps.onsdigital.uk
    port: ${cloud.application.port}
    username: admin
    password: secret

action-svc:
  actions-path: /actions
  action-plans-path: /actionplans
  connection-config:
    scheme: http
    host: actionsvc.apps.onsdigital.uk
    port: ${cloud.application.port}
    username: admin
    password: secret

collection-exercise-svc:
  collection-exercise-path: /collectionexercises/{exerciseId}
  connection-config:
    scheme: http
    host: collectionexercisesvc.apps.onsdigital.uk
    port: ${cloud.application.port}
    username: admin
    password: secret

case-distribution:
  retrieval-max: 50
  delay-milli-seconds: 500

redelivery-policy:
  maxRedeliveries: 10
  initialRedeliveryDelay: 1000
  redeliveryDelay: 1000

rabbitmq:
  username: ${cloud.services.rabbitmq.connection.username}
  password: ${cloud.services.rabbitmq.connection.password}
  host: ${cloud.services.rabbitmq.connection.host}
  port: ${cloud.services.rabbitmq.connection.port}
  virtualhost: ${cloud.services.rabbitmq.connection.virtualhost}

messaging:
  backoffInitial: 5000
  backoffMultiplier: 3
  backoffMax: 45000
  consumingThreads: 1
  pubMaxAttempts: 3
  conMaxAttempts: 3
  prefetchCount: 10
  txSize: 1

report-settings:
  cron-expression: "0 * * * * *"

swagger-settings:
  swagger-ui-active: false
  group-name: caseservice-api
  title: Case Service API
  description: API for ${project.artifactId}
  version: ${project.version}

retries:
  maxAttempts: 3
  backoff: 5000
