
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bookingCodeDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bookingCodeDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}entity">
 *       &lt;sequence>
 *         &lt;element name="bookingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingCodeTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="contract" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="serviceRequirement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trade" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="workflowType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bookingCodeDefinition", propOrder = {
    "bookingCode",
    "bookingCodeDescription",
    "bookingCodeTime",
    "contract",
    "serviceRequirement",
    "trade",
    "workflowType"
})
public class BookingCodeDefinition
    extends Entity
{

    @XmlElement(required = true)
    protected String bookingCode;
    @XmlElement(required = true)
    protected String bookingCodeDescription;
    protected int bookingCodeTime;
    @XmlElement(required = true)
    protected String contract;
    @XmlElement(defaultValue = "false")
    protected String serviceRequirement;
    protected String trade;
    @XmlElement(defaultValue = "0000")
    protected String workflowType;

    /**
     * Gets the value of the bookingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingCode() {
        return bookingCode;
    }

    /**
     * Sets the value of the bookingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingCode(String value) {
        this.bookingCode = value;
    }

    /**
     * Gets the value of the bookingCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingCodeDescription() {
        return bookingCodeDescription;
    }

    /**
     * Sets the value of the bookingCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingCodeDescription(String value) {
        this.bookingCodeDescription = value;
    }

    /**
     * Gets the value of the bookingCodeTime property.
     * 
     */
    public int getBookingCodeTime() {
        return bookingCodeTime;
    }

    /**
     * Sets the value of the bookingCodeTime property.
     * 
     */
    public void setBookingCodeTime(int value) {
        this.bookingCodeTime = value;
    }

    /**
     * Gets the value of the contract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContract(String value) {
        this.contract = value;
    }

    /**
     * Gets the value of the serviceRequirement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceRequirement() {
        return serviceRequirement;
    }

    /**
     * Sets the value of the serviceRequirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceRequirement(String value) {
        this.serviceRequirement = value;
    }

    /**
     * Gets the value of the trade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrade() {
        return trade;
    }

    /**
     * Sets the value of the trade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrade(String value) {
        this.trade = value;
    }

    /**
     * Gets the value of the workflowType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowType() {
        return workflowType;
    }

    /**
     * Sets the value of the workflowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowType(String value) {
        this.workflowType = value;
    }

}
