
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for closeSession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="closeSession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="closeSession" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbCloseSession" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "closeSession", propOrder = {
    "closeSession"
})
public class CloseSession {

    protected XmbCloseSession closeSession;

    /**
     * Gets the value of the closeSession property.
     * 
     * @return
     *     possible object is
     *     {@link XmbCloseSession }
     *     
     */
    public XmbCloseSession getCloseSession() {
        return closeSession;
    }

    /**
     * Sets the value of the closeSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbCloseSession }
     *     
     */
    public void setCloseSession(XmbCloseSession value) {
        this.closeSession = value;
    }

}
