
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for command complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="command">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}entity">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "command", propOrder = {
    "id"
})
@XmlSeeAlso({
    XmbScheduleBooking.class,
    XmbUpdateOrder.class,
    XmbGetSchedule.class,
    XmbOpenSession.class,
    XmbCompleteOrder.class,
    XmbSelectResource.class,
    XmbDeleteBooking.class,
    XmbCreateReservation.class,
    XmbUpdateLocation.class,
    XmbSelectBooking.class,
    XmbSelectAlerts.class,
    XmbSelectOrder.class,
    XmbConfirmReservation.class,
    XmbCreateOrder.class,
    XmbDeleteOrder.class,
    XmbSelectMetaData.class,
    XmbUpdateBookingCode.class,
    XmbUpdateBooking.class,
    XmbCloseSession.class,
    XmbUpdateResource.class,
    XmbCheckAvailability.class,
    XmbCreateBooking.class
})
public class Command
    extends Entity
{

    @XmlElement(defaultValue = "0")
    protected int id;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
