
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for commandResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commandResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}entity">
 *       &lt;sequence>
 *         &lt;element name="debugStackTrace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="errorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="status" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}responseStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commandResponse", propOrder = {
    "debugStackTrace",
    "errorMsg",
    "id",
    "status"
})
@XmlSeeAlso({
    XmbCompleteOrderResponse.class,
    XmbCreateBookingResponse.class,
    XmbGetScheduleResponse.class,
    XmbScheduleBookingResponse.class,
    XmbCreateOrderResponse.class,
    XmbUpdateOrderResponse.class,
    XmbSelectBookingResponse.class,
    XmbSelectAlertsResponse.class,
    XmbUpdateBookingResponse.class,
    XmbSelectResourceResponse.class,
    XmbOpenSessionResponse.class,
    XmbConfirmReservationResponse.class,
    XmbSelectMetaDataResponse.class,
    XmbCheckAvailabilityResponse.class,
    XmbUpdateLocationResponse.class,
    XmbCloseSessionResponse.class,
    XmbUpdateResourceResponse.class,
    XmbSelectOrderResponse.class,
    XmbUpdateBookingCodeResponse.class,
    XmbCreateReservationResponse.class,
    XmbDeleteOrderResponse.class,
    XmbDeleteBookingResponse.class
})
public class CommandResponse
    extends Entity
{

    protected String debugStackTrace;
    protected String errorMsg;
    @XmlElement(defaultValue = "0")
    protected int id;
    protected ResponseStatus status;

    /**
     * Gets the value of the debugStackTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebugStackTrace() {
        return debugStackTrace;
    }

    /**
     * Sets the value of the debugStackTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebugStackTrace(String value) {
        this.debugStackTrace = value;
    }

    /**
     * Gets the value of the errorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMsg() {
        return errorMsg;
    }

    /**
     * Sets the value of the errorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMsg(String value) {
        this.errorMsg = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatus }
     *     
     */
    public ResponseStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatus }
     *     
     */
    public void setStatus(ResponseStatus value) {
        this.status = value;
    }

}
