
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createReservation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createReservation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createReservation" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbCreateReservation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createReservation", propOrder = {
    "createReservation"
})
public class CreateReservation {

    protected XmbCreateReservation createReservation;

    /**
     * Gets the value of the createReservation property.
     * 
     * @return
     *     possible object is
     *     {@link XmbCreateReservation }
     *     
     */
    public XmbCreateReservation getCreateReservation() {
        return createReservation;
    }

    /**
     * Sets the value of the createReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbCreateReservation }
     *     
     */
    public void setCreateReservation(XmbCreateReservation value) {
        this.createReservation = value;
    }

}
