
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for deleteOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deleteOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deleteOrder" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbDeleteOrder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteOrder", propOrder = {
    "deleteOrder"
})
public class DeleteOrder {

    protected XmbDeleteOrder deleteOrder;

    /**
     * Gets the value of the deleteOrder property.
     * 
     * @return
     *     possible object is
     *     {@link XmbDeleteOrder }
     *     
     */
    public XmbDeleteOrder getDeleteOrder() {
        return deleteOrder;
    }

    /**
     * Sets the value of the deleteOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbDeleteOrder }
     *     
     */
    public void setDeleteOrder(XmbDeleteOrder value) {
        this.deleteOrder = value;
    }

}
