
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.ons.ctp.response.kirona.drs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XmbCompleteOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCompleteOrder");
    private final static QName _SelectAlerts_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectAlerts");
    private final static QName _XmbSelectResource_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectResource");
    private final static QName _XmbDeleteBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbDeleteBooking");
    private final static QName _XmbOpenSession_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbOpenSession");
    private final static QName _DeleteOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "deleteOrderResponse");
    private final static QName _XmbUnavailabilityReason_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUnavailabilityReason");
    private final static QName _XmbCreateOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateOrderResponse");
    private final static QName _CompleteOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "completeOrderResponse");
    private final static QName _XmbCreateReservation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateReservation");
    private final static QName _XmbOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbOrder");
    private final static QName _XmbOrderPattern_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbOrderPattern");
    private final static QName _SelectAlertsResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectAlertsResponse");
    private final static QName _XmbUpdateLocation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateLocation");
    private final static QName _XmbSelectBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectBooking");
    private final static QName _CheckAvailability_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "checkAvailability");
    private final static QName _XmbSelectAlerts_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectAlerts");
    private final static QName _XmbSelectResourceResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectResourceResponse");
    private final static QName _XmbOpenSessionResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbOpenSessionResponse");
    private final static QName _XmbCommand_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCommand");
    private final static QName _XmbUpdateOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateOrderResponse");
    private final static QName _UpdateBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateBookingResponse");
    private final static QName _XmbUpdateBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateBookingResponse");
    private final static QName _XmbSelectAlertsResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectAlertsResponse");
    private final static QName _XmbSelectBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectBookingResponse");
    private final static QName _XmbCompleteOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCompleteOrderResponse");
    private final static QName _XmbLocation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbLocation");
    private final static QName _CreateBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createBookingResponse");
    private final static QName _SelectResourceResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectResourceResponse");
    private final static QName _XmbCreateBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateBookingResponse");
    private final static QName _SelectOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectOrder");
    private final static QName _XmbSector_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSector");
    private final static QName _XmbDaySlotsInfo_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbDaySlotsInfo");
    private final static QName _SelectResource_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectResource");
    private final static QName _ScheduleBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "scheduleBooking");
    private final static QName _CreateReservation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createReservation");
    private final static QName _XmbUpdateOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateOrder");
    private final static QName _XmbGetScheduleResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbGetScheduleResponse");
    private final static QName _UpdateOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateOrder");
    private final static QName _OpenSession_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "openSession");
    private final static QName _DeleteBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "deleteBooking");
    private final static QName _ConfirmReservationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "confirmReservationResponse");
    private final static QName _XmbScheduleBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbScheduleBooking");
    private final static QName _CheckAvailabilityResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "checkAvailabilityResponse");
    private final static QName _CloseSessionResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "closeSessionResponse");
    private final static QName _XmbResourceTemplate_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbResourceTemplate");
    private final static QName _XmbGetSchedule_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbGetSchedule");
    private final static QName _XmbScheduleBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbScheduleBookingResponse");
    private final static QName _XmbBusinessDataDefinition_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbBusinessDataDefinition");
    private final static QName _XmbResource_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbResource");
    private final static QName _XmbSelectMetaData_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectMetaData");
    private final static QName _CreateReservationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createReservationResponse");
    private final static QName _DeleteOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "deleteOrder");
    private final static QName _XmbAlert_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbAlert");
    private final static QName _XmbBookingCode_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbBookingCode");
    private final static QName _XmbDeleteOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbDeleteOrderResponse");
    private final static QName _XmbUpdateBookingCode_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateBookingCode");
    private final static QName _UpdateBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateBooking");
    private final static QName _ConfirmReservation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "confirmReservation");
    private final static QName _UpdateLocation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateLocation");
    private final static QName _XmbUnavailability_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUnavailability");
    private final static QName _XmbBookingCodeDefinition_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbBookingCodeDefinition");
    private final static QName _XmbUpdateBookingCodeResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateBookingCodeResponse");
    private final static QName _GetSchedule_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "getSchedule");
    private final static QName _XmbCreateReservationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateReservationResponse");
    private final static QName _XmbCommandResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCommandResponse");
    private final static QName _XmbUpdateBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateBooking");
    private final static QName _XmbWorkingHour_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbWorkingHour");
    private final static QName _XmbCloseSession_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCloseSession");
    private final static QName _SelectMetaDataResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectMetaDataResponse");
    private final static QName _CloseSession_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "closeSession");
    private final static QName _XmbCreateBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateBooking");
    private final static QName _DeleteBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "deleteBookingResponse");
    private final static QName _XmbAbility_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbAbility");
    private final static QName _XmbBusinessData_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbBusinessData");
    private final static QName _XmbDeleteBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbDeleteBookingResponse");
    private final static QName _XmbUpdateResource_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateResource");
    private final static QName _XmbCheckAvailability_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCheckAvailability");
    private final static QName _XmbBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbBooking");
    private final static QName _UpdateLocationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateLocationResponse");
    private final static QName _XmbConfirmReservationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbConfirmReservationResponse");
    private final static QName _CreateBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createBooking");
    private final static QName _OpenSessionResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "openSessionResponse");
    private final static QName _XmbSelectOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectOrder");
    private final static QName _UpdateResource_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateResource");
    private final static QName _CompleteOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "completeOrder");
    private final static QName _ScheduleBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "scheduleBookingResponse");
    private final static QName _UpdateOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateOrderResponse");
    private final static QName _SelectBookingResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectBookingResponse");
    private final static QName _XmbCheckAvailabilityResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCheckAvailabilityResponse");
    private final static QName _XmbUpdateLocationResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateLocationResponse");
    private final static QName _XmbConfirmReservation_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbConfirmReservation");
    private final static QName _CreateOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createOrderResponse");
    private final static QName _XmbCreateOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCreateOrder");
    private final static QName _UpdateResourceResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateResourceResponse");
    private final static QName _XmbSelectMetaDataResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectMetaDataResponse");
    private final static QName _XmbAvailablePeriod_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbAvailablePeriod");
    private final static QName _UpdateBookingCodeResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateBookingCodeResponse");
    private final static QName _SelectBooking_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectBooking");
    private final static QName _XmbLocationLine_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbLocationLine");
    private final static QName _XmbCloseSessionResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbCloseSessionResponse");
    private final static QName _XmbUpdateResourceResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbUpdateResourceResponse");
    private final static QName _CreateOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "createOrder");
    private final static QName _XmbDeleteOrder_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbDeleteOrder");
    private final static QName _XmbSelectOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSelectOrderResponse");
    private final static QName _UpdateBookingCode_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "updateBookingCode");
    private final static QName _XmbSlotInfo_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbSlotInfo");
    private final static QName _SelectOrderResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectOrderResponse");
    private final static QName _GetScheduleResponse_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "getScheduleResponse");
    private final static QName _SelectMetaData_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "selectMetaData");
    private final static QName _XmbAvailableDay_QNAME = new QName("http://autogenerated.OTWebServiceApi.xmbrace.com/", "XmbAvailableDay");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.ons.ctp.response.kirona.drs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateBookingResponse }
     * 
     */
    public CreateBookingResponse createCreateBookingResponse() {
        return new CreateBookingResponse();
    }

    /**
     * Create an instance of {@link SelectResourceResponse }
     * 
     */
    public SelectResourceResponse createSelectResourceResponse() {
        return new SelectResourceResponse();
    }

    /**
     * Create an instance of {@link XmbCompleteOrderResponse }
     * 
     */
    public XmbCompleteOrderResponse createXmbCompleteOrderResponse() {
        return new XmbCompleteOrderResponse();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link DaySlotsInfo }
     * 
     */
    public DaySlotsInfo createDaySlotsInfo() {
        return new DaySlotsInfo();
    }

    /**
     * Create an instance of {@link SelectResource }
     * 
     */
    public SelectResource createSelectResource() {
        return new SelectResource();
    }

    /**
     * Create an instance of {@link ScheduleBooking }
     * 
     */
    public ScheduleBooking createScheduleBooking() {
        return new ScheduleBooking();
    }

    /**
     * Create an instance of {@link SelectOrder }
     * 
     */
    public SelectOrder createSelectOrder() {
        return new SelectOrder();
    }

    /**
     * Create an instance of {@link XmbCreateBookingResponse }
     * 
     */
    public XmbCreateBookingResponse createXmbCreateBookingResponse() {
        return new XmbCreateBookingResponse();
    }

    /**
     * Create an instance of {@link Sector }
     * 
     */
    public Sector createSector() {
        return new Sector();
    }

    /**
     * Create an instance of {@link OpenSession }
     * 
     */
    public OpenSession createOpenSession() {
        return new OpenSession();
    }

    /**
     * Create an instance of {@link UpdateOrder }
     * 
     */
    public UpdateOrder createUpdateOrder() {
        return new UpdateOrder();
    }

    /**
     * Create an instance of {@link DeleteBooking }
     * 
     */
    public DeleteBooking createDeleteBooking() {
        return new DeleteBooking();
    }

    /**
     * Create an instance of {@link ConfirmReservationResponse }
     * 
     */
    public ConfirmReservationResponse createConfirmReservationResponse() {
        return new ConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link XmbScheduleBooking }
     * 
     */
    public XmbScheduleBooking createXmbScheduleBooking() {
        return new XmbScheduleBooking();
    }

    /**
     * Create an instance of {@link XmbUpdateOrder }
     * 
     */
    public XmbUpdateOrder createXmbUpdateOrder() {
        return new XmbUpdateOrder();
    }

    /**
     * Create an instance of {@link CreateReservation }
     * 
     */
    public CreateReservation createCreateReservation() {
        return new CreateReservation();
    }

    /**
     * Create an instance of {@link XmbGetScheduleResponse }
     * 
     */
    public XmbGetScheduleResponse createXmbGetScheduleResponse() {
        return new XmbGetScheduleResponse();
    }

    /**
     * Create an instance of {@link XmbScheduleBookingResponse }
     * 
     */
    public XmbScheduleBookingResponse createXmbScheduleBookingResponse() {
        return new XmbScheduleBookingResponse();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link BusinessDataDefinition }
     * 
     */
    public BusinessDataDefinition createBusinessDataDefinition() {
        return new BusinessDataDefinition();
    }

    /**
     * Create an instance of {@link CheckAvailabilityResponse }
     * 
     */
    public CheckAvailabilityResponse createCheckAvailabilityResponse() {
        return new CheckAvailabilityResponse();
    }

    /**
     * Create an instance of {@link CloseSessionResponse }
     * 
     */
    public CloseSessionResponse createCloseSessionResponse() {
        return new CloseSessionResponse();
    }

    /**
     * Create an instance of {@link ResourceTemplate }
     * 
     */
    public ResourceTemplate createResourceTemplate() {
        return new ResourceTemplate();
    }

    /**
     * Create an instance of {@link XmbGetSchedule }
     * 
     */
    public XmbGetSchedule createXmbGetSchedule() {
        return new XmbGetSchedule();
    }

    /**
     * Create an instance of {@link XmbOpenSession }
     * 
     */
    public XmbOpenSession createXmbOpenSession() {
        return new XmbOpenSession();
    }

    /**
     * Create an instance of {@link DeleteOrderResponse }
     * 
     */
    public DeleteOrderResponse createDeleteOrderResponse() {
        return new DeleteOrderResponse();
    }

    /**
     * Create an instance of {@link UnavailabilityReason }
     * 
     */
    public UnavailabilityReason createUnavailabilityReason() {
        return new UnavailabilityReason();
    }

    /**
     * Create an instance of {@link XmbCreateOrderResponse }
     * 
     */
    public XmbCreateOrderResponse createXmbCreateOrderResponse() {
        return new XmbCreateOrderResponse();
    }

    /**
     * Create an instance of {@link XmbCompleteOrder }
     * 
     */
    public XmbCompleteOrder createXmbCompleteOrder() {
        return new XmbCompleteOrder();
    }

    /**
     * Create an instance of {@link XmbSelectResource }
     * 
     */
    public XmbSelectResource createXmbSelectResource() {
        return new XmbSelectResource();
    }

    /**
     * Create an instance of {@link SelectAlerts }
     * 
     */
    public SelectAlerts createSelectAlerts() {
        return new SelectAlerts();
    }

    /**
     * Create an instance of {@link XmbDeleteBooking }
     * 
     */
    public XmbDeleteBooking createXmbDeleteBooking() {
        return new XmbDeleteBooking();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link SelectAlertsResponse }
     * 
     */
    public SelectAlertsResponse createSelectAlertsResponse() {
        return new SelectAlertsResponse();
    }

    /**
     * Create an instance of {@link OrderPattern }
     * 
     */
    public OrderPattern createOrderPattern() {
        return new OrderPattern();
    }

    /**
     * Create an instance of {@link XmbCreateReservation }
     * 
     */
    public XmbCreateReservation createXmbCreateReservation() {
        return new XmbCreateReservation();
    }

    /**
     * Create an instance of {@link CompleteOrderResponse }
     * 
     */
    public CompleteOrderResponse createCompleteOrderResponse() {
        return new CompleteOrderResponse();
    }

    /**
     * Create an instance of {@link XmbUpdateLocation }
     * 
     */
    public XmbUpdateLocation createXmbUpdateLocation() {
        return new XmbUpdateLocation();
    }

    /**
     * Create an instance of {@link XmbSelectBooking }
     * 
     */
    public XmbSelectBooking createXmbSelectBooking() {
        return new XmbSelectBooking();
    }

    /**
     * Create an instance of {@link Command }
     * 
     */
    public Command createCommand() {
        return new Command();
    }

    /**
     * Create an instance of {@link XmbUpdateOrderResponse }
     * 
     */
    public XmbUpdateOrderResponse createXmbUpdateOrderResponse() {
        return new XmbUpdateOrderResponse();
    }

    /**
     * Create an instance of {@link XmbSelectBookingResponse }
     * 
     */
    public XmbSelectBookingResponse createXmbSelectBookingResponse() {
        return new XmbSelectBookingResponse();
    }

    /**
     * Create an instance of {@link XmbSelectAlertsResponse }
     * 
     */
    public XmbSelectAlertsResponse createXmbSelectAlertsResponse() {
        return new XmbSelectAlertsResponse();
    }

    /**
     * Create an instance of {@link XmbUpdateBookingResponse }
     * 
     */
    public XmbUpdateBookingResponse createXmbUpdateBookingResponse() {
        return new XmbUpdateBookingResponse();
    }

    /**
     * Create an instance of {@link UpdateBookingResponse }
     * 
     */
    public UpdateBookingResponse createUpdateBookingResponse() {
        return new UpdateBookingResponse();
    }

    /**
     * Create an instance of {@link XmbSelectResourceResponse }
     * 
     */
    public XmbSelectResourceResponse createXmbSelectResourceResponse() {
        return new XmbSelectResourceResponse();
    }

    /**
     * Create an instance of {@link CheckAvailability }
     * 
     */
    public CheckAvailability createCheckAvailability() {
        return new CheckAvailability();
    }

    /**
     * Create an instance of {@link XmbSelectAlerts }
     * 
     */
    public XmbSelectAlerts createXmbSelectAlerts() {
        return new XmbSelectAlerts();
    }

    /**
     * Create an instance of {@link XmbOpenSessionResponse }
     * 
     */
    public XmbOpenSessionResponse createXmbOpenSessionResponse() {
        return new XmbOpenSessionResponse();
    }

    /**
     * Create an instance of {@link OpenSessionResponse }
     * 
     */
    public OpenSessionResponse createOpenSessionResponse() {
        return new OpenSessionResponse();
    }

    /**
     * Create an instance of {@link XmbSelectOrder }
     * 
     */
    public XmbSelectOrder createXmbSelectOrder() {
        return new XmbSelectOrder();
    }

    /**
     * Create an instance of {@link CompleteOrder }
     * 
     */
    public CompleteOrder createCompleteOrder() {
        return new CompleteOrder();
    }

    /**
     * Create an instance of {@link ScheduleBookingResponse }
     * 
     */
    public ScheduleBookingResponse createScheduleBookingResponse() {
        return new ScheduleBookingResponse();
    }

    /**
     * Create an instance of {@link UpdateResource }
     * 
     */
    public UpdateResource createUpdateResource() {
        return new UpdateResource();
    }

    /**
     * Create an instance of {@link UpdateOrderResponse }
     * 
     */
    public UpdateOrderResponse createUpdateOrderResponse() {
        return new UpdateOrderResponse();
    }

    /**
     * Create an instance of {@link XmbConfirmReservationResponse }
     * 
     */
    public XmbConfirmReservationResponse createXmbConfirmReservationResponse() {
        return new XmbConfirmReservationResponse();
    }

    /**
     * Create an instance of {@link CreateBooking }
     * 
     */
    public CreateBooking createCreateBooking() {
        return new CreateBooking();
    }

    /**
     * Create an instance of {@link CreateOrderResponse }
     * 
     */
    public CreateOrderResponse createCreateOrderResponse() {
        return new CreateOrderResponse();
    }

    /**
     * Create an instance of {@link XmbConfirmReservation }
     * 
     */
    public XmbConfirmReservation createXmbConfirmReservation() {
        return new XmbConfirmReservation();
    }

    /**
     * Create an instance of {@link XmbCreateOrder }
     * 
     */
    public XmbCreateOrder createXmbCreateOrder() {
        return new XmbCreateOrder();
    }

    /**
     * Create an instance of {@link UpdateResourceResponse }
     * 
     */
    public UpdateResourceResponse createUpdateResourceResponse() {
        return new UpdateResourceResponse();
    }

    /**
     * Create an instance of {@link AvailablePeriod }
     * 
     */
    public AvailablePeriod createAvailablePeriod() {
        return new AvailablePeriod();
    }

    /**
     * Create an instance of {@link UpdateBookingCodeResponse }
     * 
     */
    public UpdateBookingCodeResponse createUpdateBookingCodeResponse() {
        return new UpdateBookingCodeResponse();
    }

    /**
     * Create an instance of {@link XmbSelectMetaDataResponse }
     * 
     */
    public XmbSelectMetaDataResponse createXmbSelectMetaDataResponse() {
        return new XmbSelectMetaDataResponse();
    }

    /**
     * Create an instance of {@link SelectBookingResponse }
     * 
     */
    public SelectBookingResponse createSelectBookingResponse() {
        return new SelectBookingResponse();
    }

    /**
     * Create an instance of {@link XmbCheckAvailabilityResponse }
     * 
     */
    public XmbCheckAvailabilityResponse createXmbCheckAvailabilityResponse() {
        return new XmbCheckAvailabilityResponse();
    }

    /**
     * Create an instance of {@link XmbUpdateLocationResponse }
     * 
     */
    public XmbUpdateLocationResponse createXmbUpdateLocationResponse() {
        return new XmbUpdateLocationResponse();
    }

    /**
     * Create an instance of {@link XmbDeleteOrder }
     * 
     */
    public XmbDeleteOrder createXmbDeleteOrder() {
        return new XmbDeleteOrder();
    }

    /**
     * Create an instance of {@link SelectBooking }
     * 
     */
    public SelectBooking createSelectBooking() {
        return new SelectBooking();
    }

    /**
     * Create an instance of {@link LocationLine }
     * 
     */
    public LocationLine createLocationLine() {
        return new LocationLine();
    }

    /**
     * Create an instance of {@link XmbCloseSessionResponse }
     * 
     */
    public XmbCloseSessionResponse createXmbCloseSessionResponse() {
        return new XmbCloseSessionResponse();
    }

    /**
     * Create an instance of {@link XmbUpdateResourceResponse }
     * 
     */
    public XmbUpdateResourceResponse createXmbUpdateResourceResponse() {
        return new XmbUpdateResourceResponse();
    }

    /**
     * Create an instance of {@link CreateOrder }
     * 
     */
    public CreateOrder createCreateOrder() {
        return new CreateOrder();
    }

    /**
     * Create an instance of {@link SlotInfo }
     * 
     */
    public SlotInfo createSlotInfo() {
        return new SlotInfo();
    }

    /**
     * Create an instance of {@link SelectOrderResponse }
     * 
     */
    public SelectOrderResponse createSelectOrderResponse() {
        return new SelectOrderResponse();
    }

    /**
     * Create an instance of {@link GetScheduleResponse }
     * 
     */
    public GetScheduleResponse createGetScheduleResponse() {
        return new GetScheduleResponse();
    }

    /**
     * Create an instance of {@link SelectMetaData }
     * 
     */
    public SelectMetaData createSelectMetaData() {
        return new SelectMetaData();
    }

    /**
     * Create an instance of {@link AvailableDay }
     * 
     */
    public AvailableDay createAvailableDay() {
        return new AvailableDay();
    }

    /**
     * Create an instance of {@link UpdateBookingCode }
     * 
     */
    public UpdateBookingCode createUpdateBookingCode() {
        return new UpdateBookingCode();
    }

    /**
     * Create an instance of {@link XmbSelectOrderResponse }
     * 
     */
    public XmbSelectOrderResponse createXmbSelectOrderResponse() {
        return new XmbSelectOrderResponse();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link Alert }
     * 
     */
    public Alert createAlert() {
        return new Alert();
    }

    /**
     * Create an instance of {@link DeleteOrder }
     * 
     */
    public DeleteOrder createDeleteOrder() {
        return new DeleteOrder();
    }

    /**
     * Create an instance of {@link BookingCode }
     * 
     */
    public BookingCode createBookingCode() {
        return new BookingCode();
    }

    /**
     * Create an instance of {@link XmbSelectMetaData }
     * 
     */
    public XmbSelectMetaData createXmbSelectMetaData() {
        return new XmbSelectMetaData();
    }

    /**
     * Create an instance of {@link XmbUpdateBookingCodeResponse }
     * 
     */
    public XmbUpdateBookingCodeResponse createXmbUpdateBookingCodeResponse() {
        return new XmbUpdateBookingCodeResponse();
    }

    /**
     * Create an instance of {@link GetSchedule }
     * 
     */
    public GetSchedule createGetSchedule() {
        return new GetSchedule();
    }

    /**
     * Create an instance of {@link XmbCreateReservationResponse }
     * 
     */
    public XmbCreateReservationResponse createXmbCreateReservationResponse() {
        return new XmbCreateReservationResponse();
    }

    /**
     * Create an instance of {@link CommandResponse }
     * 
     */
    public CommandResponse createCommandResponse() {
        return new CommandResponse();
    }

    /**
     * Create an instance of {@link XmbDeleteOrderResponse }
     * 
     */
    public XmbDeleteOrderResponse createXmbDeleteOrderResponse() {
        return new XmbDeleteOrderResponse();
    }

    /**
     * Create an instance of {@link XmbUpdateBookingCode }
     * 
     */
    public XmbUpdateBookingCode createXmbUpdateBookingCode() {
        return new XmbUpdateBookingCode();
    }

    /**
     * Create an instance of {@link UpdateBooking }
     * 
     */
    public UpdateBooking createUpdateBooking() {
        return new UpdateBooking();
    }

    /**
     * Create an instance of {@link ConfirmReservation }
     * 
     */
    public ConfirmReservation createConfirmReservation() {
        return new ConfirmReservation();
    }

    /**
     * Create an instance of {@link UpdateLocation }
     * 
     */
    public UpdateLocation createUpdateLocation() {
        return new UpdateLocation();
    }

    /**
     * Create an instance of {@link BookingCodeDefinition }
     * 
     */
    public BookingCodeDefinition createBookingCodeDefinition() {
        return new BookingCodeDefinition();
    }

    /**
     * Create an instance of {@link Unavailability }
     * 
     */
    public Unavailability createUnavailability() {
        return new Unavailability();
    }

    /**
     * Create an instance of {@link CloseSession }
     * 
     */
    public CloseSession createCloseSession() {
        return new CloseSession();
    }

    /**
     * Create an instance of {@link XmbUpdateBooking }
     * 
     */
    public XmbUpdateBooking createXmbUpdateBooking() {
        return new XmbUpdateBooking();
    }

    /**
     * Create an instance of {@link XmbCloseSession }
     * 
     */
    public XmbCloseSession createXmbCloseSession() {
        return new XmbCloseSession();
    }

    /**
     * Create an instance of {@link WorkingHour }
     * 
     */
    public WorkingHour createWorkingHour() {
        return new WorkingHour();
    }

    /**
     * Create an instance of {@link SelectMetaDataResponse }
     * 
     */
    public SelectMetaDataResponse createSelectMetaDataResponse() {
        return new SelectMetaDataResponse();
    }

    /**
     * Create an instance of {@link XmbDeleteBookingResponse }
     * 
     */
    public XmbDeleteBookingResponse createXmbDeleteBookingResponse() {
        return new XmbDeleteBookingResponse();
    }

    /**
     * Create an instance of {@link BusinessData }
     * 
     */
    public BusinessData createBusinessData() {
        return new BusinessData();
    }

    /**
     * Create an instance of {@link XmbUpdateResource }
     * 
     */
    public XmbUpdateResource createXmbUpdateResource() {
        return new XmbUpdateResource();
    }

    /**
     * Create an instance of {@link Booking }
     * 
     */
    public Booking createBooking() {
        return new Booking();
    }

    /**
     * Create an instance of {@link XmbCheckAvailability }
     * 
     */
    public XmbCheckAvailability createXmbCheckAvailability() {
        return new XmbCheckAvailability();
    }

    /**
     * Create an instance of {@link UpdateLocationResponse }
     * 
     */
    public UpdateLocationResponse createUpdateLocationResponse() {
        return new UpdateLocationResponse();
    }

    /**
     * Create an instance of {@link XmbCreateBooking }
     * 
     */
    public XmbCreateBooking createXmbCreateBooking() {
        return new XmbCreateBooking();
    }

    /**
     * Create an instance of {@link DeleteBookingResponse }
     * 
     */
    public DeleteBookingResponse createDeleteBookingResponse() {
        return new DeleteBookingResponse();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCompleteOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCompleteOrder")
    public JAXBElement<XmbCompleteOrder> createXmbCompleteOrder(XmbCompleteOrder value) {
        return new JAXBElement<XmbCompleteOrder>(_XmbCompleteOrder_QNAME, XmbCompleteOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectAlerts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectAlerts")
    public JAXBElement<SelectAlerts> createSelectAlerts(SelectAlerts value) {
        return new JAXBElement<SelectAlerts>(_SelectAlerts_QNAME, SelectAlerts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectResource")
    public JAXBElement<XmbSelectResource> createXmbSelectResource(XmbSelectResource value) {
        return new JAXBElement<XmbSelectResource>(_XmbSelectResource_QNAME, XmbSelectResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbDeleteBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbDeleteBooking")
    public JAXBElement<XmbDeleteBooking> createXmbDeleteBooking(XmbDeleteBooking value) {
        return new JAXBElement<XmbDeleteBooking>(_XmbDeleteBooking_QNAME, XmbDeleteBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbOpenSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbOpenSession")
    public JAXBElement<XmbOpenSession> createXmbOpenSession(XmbOpenSession value) {
        return new JAXBElement<XmbOpenSession>(_XmbOpenSession_QNAME, XmbOpenSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "deleteOrderResponse")
    public JAXBElement<DeleteOrderResponse> createDeleteOrderResponse(DeleteOrderResponse value) {
        return new JAXBElement<DeleteOrderResponse>(_DeleteOrderResponse_QNAME, DeleteOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnavailabilityReason }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUnavailabilityReason")
    public JAXBElement<UnavailabilityReason> createXmbUnavailabilityReason(UnavailabilityReason value) {
        return new JAXBElement<UnavailabilityReason>(_XmbUnavailabilityReason_QNAME, UnavailabilityReason.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateOrderResponse")
    public JAXBElement<XmbCreateOrderResponse> createXmbCreateOrderResponse(XmbCreateOrderResponse value) {
        return new JAXBElement<XmbCreateOrderResponse>(_XmbCreateOrderResponse_QNAME, XmbCreateOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "completeOrderResponse")
    public JAXBElement<CompleteOrderResponse> createCompleteOrderResponse(CompleteOrderResponse value) {
        return new JAXBElement<CompleteOrderResponse>(_CompleteOrderResponse_QNAME, CompleteOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateReservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateReservation")
    public JAXBElement<XmbCreateReservation> createXmbCreateReservation(XmbCreateReservation value) {
        return new JAXBElement<XmbCreateReservation>(_XmbCreateReservation_QNAME, XmbCreateReservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbOrder")
    public JAXBElement<Order> createXmbOrder(Order value) {
        return new JAXBElement<Order>(_XmbOrder_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderPattern }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbOrderPattern")
    public JAXBElement<OrderPattern> createXmbOrderPattern(OrderPattern value) {
        return new JAXBElement<OrderPattern>(_XmbOrderPattern_QNAME, OrderPattern.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectAlertsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectAlertsResponse")
    public JAXBElement<SelectAlertsResponse> createSelectAlertsResponse(SelectAlertsResponse value) {
        return new JAXBElement<SelectAlertsResponse>(_SelectAlertsResponse_QNAME, SelectAlertsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateLocation")
    public JAXBElement<XmbUpdateLocation> createXmbUpdateLocation(XmbUpdateLocation value) {
        return new JAXBElement<XmbUpdateLocation>(_XmbUpdateLocation_QNAME, XmbUpdateLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectBooking")
    public JAXBElement<XmbSelectBooking> createXmbSelectBooking(XmbSelectBooking value) {
        return new JAXBElement<XmbSelectBooking>(_XmbSelectBooking_QNAME, XmbSelectBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAvailability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "checkAvailability")
    public JAXBElement<CheckAvailability> createCheckAvailability(CheckAvailability value) {
        return new JAXBElement<CheckAvailability>(_CheckAvailability_QNAME, CheckAvailability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectAlerts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectAlerts")
    public JAXBElement<XmbSelectAlerts> createXmbSelectAlerts(XmbSelectAlerts value) {
        return new JAXBElement<XmbSelectAlerts>(_XmbSelectAlerts_QNAME, XmbSelectAlerts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectResourceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectResourceResponse")
    public JAXBElement<XmbSelectResourceResponse> createXmbSelectResourceResponse(XmbSelectResourceResponse value) {
        return new JAXBElement<XmbSelectResourceResponse>(_XmbSelectResourceResponse_QNAME, XmbSelectResourceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbOpenSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbOpenSessionResponse")
    public JAXBElement<XmbOpenSessionResponse> createXmbOpenSessionResponse(XmbOpenSessionResponse value) {
        return new JAXBElement<XmbOpenSessionResponse>(_XmbOpenSessionResponse_QNAME, XmbOpenSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Command }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCommand")
    public JAXBElement<Command> createXmbCommand(Command value) {
        return new JAXBElement<Command>(_XmbCommand_QNAME, Command.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateOrderResponse")
    public JAXBElement<XmbUpdateOrderResponse> createXmbUpdateOrderResponse(XmbUpdateOrderResponse value) {
        return new JAXBElement<XmbUpdateOrderResponse>(_XmbUpdateOrderResponse_QNAME, XmbUpdateOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateBookingResponse")
    public JAXBElement<UpdateBookingResponse> createUpdateBookingResponse(UpdateBookingResponse value) {
        return new JAXBElement<UpdateBookingResponse>(_UpdateBookingResponse_QNAME, UpdateBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateBookingResponse")
    public JAXBElement<XmbUpdateBookingResponse> createXmbUpdateBookingResponse(XmbUpdateBookingResponse value) {
        return new JAXBElement<XmbUpdateBookingResponse>(_XmbUpdateBookingResponse_QNAME, XmbUpdateBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectAlertsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectAlertsResponse")
    public JAXBElement<XmbSelectAlertsResponse> createXmbSelectAlertsResponse(XmbSelectAlertsResponse value) {
        return new JAXBElement<XmbSelectAlertsResponse>(_XmbSelectAlertsResponse_QNAME, XmbSelectAlertsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectBookingResponse")
    public JAXBElement<XmbSelectBookingResponse> createXmbSelectBookingResponse(XmbSelectBookingResponse value) {
        return new JAXBElement<XmbSelectBookingResponse>(_XmbSelectBookingResponse_QNAME, XmbSelectBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCompleteOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCompleteOrderResponse")
    public JAXBElement<XmbCompleteOrderResponse> createXmbCompleteOrderResponse(XmbCompleteOrderResponse value) {
        return new JAXBElement<XmbCompleteOrderResponse>(_XmbCompleteOrderResponse_QNAME, XmbCompleteOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbLocation")
    public JAXBElement<Location> createXmbLocation(Location value) {
        return new JAXBElement<Location>(_XmbLocation_QNAME, Location.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createBookingResponse")
    public JAXBElement<CreateBookingResponse> createCreateBookingResponse(CreateBookingResponse value) {
        return new JAXBElement<CreateBookingResponse>(_CreateBookingResponse_QNAME, CreateBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectResourceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectResourceResponse")
    public JAXBElement<SelectResourceResponse> createSelectResourceResponse(SelectResourceResponse value) {
        return new JAXBElement<SelectResourceResponse>(_SelectResourceResponse_QNAME, SelectResourceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateBookingResponse")
    public JAXBElement<XmbCreateBookingResponse> createXmbCreateBookingResponse(XmbCreateBookingResponse value) {
        return new JAXBElement<XmbCreateBookingResponse>(_XmbCreateBookingResponse_QNAME, XmbCreateBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectOrder")
    public JAXBElement<SelectOrder> createSelectOrder(SelectOrder value) {
        return new JAXBElement<SelectOrder>(_SelectOrder_QNAME, SelectOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sector }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSector")
    public JAXBElement<Sector> createXmbSector(Sector value) {
        return new JAXBElement<Sector>(_XmbSector_QNAME, Sector.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DaySlotsInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbDaySlotsInfo")
    public JAXBElement<DaySlotsInfo> createXmbDaySlotsInfo(DaySlotsInfo value) {
        return new JAXBElement<DaySlotsInfo>(_XmbDaySlotsInfo_QNAME, DaySlotsInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectResource")
    public JAXBElement<SelectResource> createSelectResource(SelectResource value) {
        return new JAXBElement<SelectResource>(_SelectResource_QNAME, SelectResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "scheduleBooking")
    public JAXBElement<ScheduleBooking> createScheduleBooking(ScheduleBooking value) {
        return new JAXBElement<ScheduleBooking>(_ScheduleBooking_QNAME, ScheduleBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateReservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createReservation")
    public JAXBElement<CreateReservation> createCreateReservation(CreateReservation value) {
        return new JAXBElement<CreateReservation>(_CreateReservation_QNAME, CreateReservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateOrder")
    public JAXBElement<XmbUpdateOrder> createXmbUpdateOrder(XmbUpdateOrder value) {
        return new JAXBElement<XmbUpdateOrder>(_XmbUpdateOrder_QNAME, XmbUpdateOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbGetScheduleResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbGetScheduleResponse")
    public JAXBElement<XmbGetScheduleResponse> createXmbGetScheduleResponse(XmbGetScheduleResponse value) {
        return new JAXBElement<XmbGetScheduleResponse>(_XmbGetScheduleResponse_QNAME, XmbGetScheduleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateOrder")
    public JAXBElement<UpdateOrder> createUpdateOrder(UpdateOrder value) {
        return new JAXBElement<UpdateOrder>(_UpdateOrder_QNAME, UpdateOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "openSession")
    public JAXBElement<OpenSession> createOpenSession(OpenSession value) {
        return new JAXBElement<OpenSession>(_OpenSession_QNAME, OpenSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "deleteBooking")
    public JAXBElement<DeleteBooking> createDeleteBooking(DeleteBooking value) {
        return new JAXBElement<DeleteBooking>(_DeleteBooking_QNAME, DeleteBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmReservationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "confirmReservationResponse")
    public JAXBElement<ConfirmReservationResponse> createConfirmReservationResponse(ConfirmReservationResponse value) {
        return new JAXBElement<ConfirmReservationResponse>(_ConfirmReservationResponse_QNAME, ConfirmReservationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbScheduleBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbScheduleBooking")
    public JAXBElement<XmbScheduleBooking> createXmbScheduleBooking(XmbScheduleBooking value) {
        return new JAXBElement<XmbScheduleBooking>(_XmbScheduleBooking_QNAME, XmbScheduleBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAvailabilityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "checkAvailabilityResponse")
    public JAXBElement<CheckAvailabilityResponse> createCheckAvailabilityResponse(CheckAvailabilityResponse value) {
        return new JAXBElement<CheckAvailabilityResponse>(_CheckAvailabilityResponse_QNAME, CheckAvailabilityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "closeSessionResponse")
    public JAXBElement<CloseSessionResponse> createCloseSessionResponse(CloseSessionResponse value) {
        return new JAXBElement<CloseSessionResponse>(_CloseSessionResponse_QNAME, CloseSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbResourceTemplate")
    public JAXBElement<ResourceTemplate> createXmbResourceTemplate(ResourceTemplate value) {
        return new JAXBElement<ResourceTemplate>(_XmbResourceTemplate_QNAME, ResourceTemplate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbGetSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbGetSchedule")
    public JAXBElement<XmbGetSchedule> createXmbGetSchedule(XmbGetSchedule value) {
        return new JAXBElement<XmbGetSchedule>(_XmbGetSchedule_QNAME, XmbGetSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbScheduleBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbScheduleBookingResponse")
    public JAXBElement<XmbScheduleBookingResponse> createXmbScheduleBookingResponse(XmbScheduleBookingResponse value) {
        return new JAXBElement<XmbScheduleBookingResponse>(_XmbScheduleBookingResponse_QNAME, XmbScheduleBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessDataDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbBusinessDataDefinition")
    public JAXBElement<BusinessDataDefinition> createXmbBusinessDataDefinition(BusinessDataDefinition value) {
        return new JAXBElement<BusinessDataDefinition>(_XmbBusinessDataDefinition_QNAME, BusinessDataDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Resource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbResource")
    public JAXBElement<Resource> createXmbResource(Resource value) {
        return new JAXBElement<Resource>(_XmbResource_QNAME, Resource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectMetaData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectMetaData")
    public JAXBElement<XmbSelectMetaData> createXmbSelectMetaData(XmbSelectMetaData value) {
        return new JAXBElement<XmbSelectMetaData>(_XmbSelectMetaData_QNAME, XmbSelectMetaData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateReservationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createReservationResponse")
    public JAXBElement<CreateReservationResponse> createCreateReservationResponse(CreateReservationResponse value) {
        return new JAXBElement<CreateReservationResponse>(_CreateReservationResponse_QNAME, CreateReservationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "deleteOrder")
    public JAXBElement<DeleteOrder> createDeleteOrder(DeleteOrder value) {
        return new JAXBElement<DeleteOrder>(_DeleteOrder_QNAME, DeleteOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Alert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbAlert")
    public JAXBElement<Alert> createXmbAlert(Alert value) {
        return new JAXBElement<Alert>(_XmbAlert_QNAME, Alert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookingCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbBookingCode")
    public JAXBElement<BookingCode> createXmbBookingCode(BookingCode value) {
        return new JAXBElement<BookingCode>(_XmbBookingCode_QNAME, BookingCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbDeleteOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbDeleteOrderResponse")
    public JAXBElement<XmbDeleteOrderResponse> createXmbDeleteOrderResponse(XmbDeleteOrderResponse value) {
        return new JAXBElement<XmbDeleteOrderResponse>(_XmbDeleteOrderResponse_QNAME, XmbDeleteOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateBookingCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateBookingCode")
    public JAXBElement<XmbUpdateBookingCode> createXmbUpdateBookingCode(XmbUpdateBookingCode value) {
        return new JAXBElement<XmbUpdateBookingCode>(_XmbUpdateBookingCode_QNAME, XmbUpdateBookingCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateBooking")
    public JAXBElement<UpdateBooking> createUpdateBooking(UpdateBooking value) {
        return new JAXBElement<UpdateBooking>(_UpdateBooking_QNAME, UpdateBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmReservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "confirmReservation")
    public JAXBElement<ConfirmReservation> createConfirmReservation(ConfirmReservation value) {
        return new JAXBElement<ConfirmReservation>(_ConfirmReservation_QNAME, ConfirmReservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateLocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateLocation")
    public JAXBElement<UpdateLocation> createUpdateLocation(UpdateLocation value) {
        return new JAXBElement<UpdateLocation>(_UpdateLocation_QNAME, UpdateLocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Unavailability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUnavailability")
    public JAXBElement<Unavailability> createXmbUnavailability(Unavailability value) {
        return new JAXBElement<Unavailability>(_XmbUnavailability_QNAME, Unavailability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BookingCodeDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbBookingCodeDefinition")
    public JAXBElement<BookingCodeDefinition> createXmbBookingCodeDefinition(BookingCodeDefinition value) {
        return new JAXBElement<BookingCodeDefinition>(_XmbBookingCodeDefinition_QNAME, BookingCodeDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateBookingCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateBookingCodeResponse")
    public JAXBElement<XmbUpdateBookingCodeResponse> createXmbUpdateBookingCodeResponse(XmbUpdateBookingCodeResponse value) {
        return new JAXBElement<XmbUpdateBookingCodeResponse>(_XmbUpdateBookingCodeResponse_QNAME, XmbUpdateBookingCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "getSchedule")
    public JAXBElement<GetSchedule> createGetSchedule(GetSchedule value) {
        return new JAXBElement<GetSchedule>(_GetSchedule_QNAME, GetSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateReservationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateReservationResponse")
    public JAXBElement<XmbCreateReservationResponse> createXmbCreateReservationResponse(XmbCreateReservationResponse value) {
        return new JAXBElement<XmbCreateReservationResponse>(_XmbCreateReservationResponse_QNAME, XmbCreateReservationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommandResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCommandResponse")
    public JAXBElement<CommandResponse> createXmbCommandResponse(CommandResponse value) {
        return new JAXBElement<CommandResponse>(_XmbCommandResponse_QNAME, CommandResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateBooking")
    public JAXBElement<XmbUpdateBooking> createXmbUpdateBooking(XmbUpdateBooking value) {
        return new JAXBElement<XmbUpdateBooking>(_XmbUpdateBooking_QNAME, XmbUpdateBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkingHour }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbWorkingHour")
    public JAXBElement<WorkingHour> createXmbWorkingHour(WorkingHour value) {
        return new JAXBElement<WorkingHour>(_XmbWorkingHour_QNAME, WorkingHour.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCloseSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCloseSession")
    public JAXBElement<XmbCloseSession> createXmbCloseSession(XmbCloseSession value) {
        return new JAXBElement<XmbCloseSession>(_XmbCloseSession_QNAME, XmbCloseSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectMetaDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectMetaDataResponse")
    public JAXBElement<SelectMetaDataResponse> createSelectMetaDataResponse(SelectMetaDataResponse value) {
        return new JAXBElement<SelectMetaDataResponse>(_SelectMetaDataResponse_QNAME, SelectMetaDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseSession }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "closeSession")
    public JAXBElement<CloseSession> createCloseSession(CloseSession value) {
        return new JAXBElement<CloseSession>(_CloseSession_QNAME, CloseSession.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateBooking")
    public JAXBElement<XmbCreateBooking> createXmbCreateBooking(XmbCreateBooking value) {
        return new JAXBElement<XmbCreateBooking>(_XmbCreateBooking_QNAME, XmbCreateBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "deleteBookingResponse")
    public JAXBElement<DeleteBookingResponse> createDeleteBookingResponse(DeleteBookingResponse value) {
        return new JAXBElement<DeleteBookingResponse>(_DeleteBookingResponse_QNAME, DeleteBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbAbility")
    public JAXBElement<Ability> createXmbAbility(Ability value) {
        return new JAXBElement<Ability>(_XmbAbility_QNAME, Ability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbBusinessData")
    public JAXBElement<BusinessData> createXmbBusinessData(BusinessData value) {
        return new JAXBElement<BusinessData>(_XmbBusinessData_QNAME, BusinessData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbDeleteBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbDeleteBookingResponse")
    public JAXBElement<XmbDeleteBookingResponse> createXmbDeleteBookingResponse(XmbDeleteBookingResponse value) {
        return new JAXBElement<XmbDeleteBookingResponse>(_XmbDeleteBookingResponse_QNAME, XmbDeleteBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateResource")
    public JAXBElement<XmbUpdateResource> createXmbUpdateResource(XmbUpdateResource value) {
        return new JAXBElement<XmbUpdateResource>(_XmbUpdateResource_QNAME, XmbUpdateResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCheckAvailability }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCheckAvailability")
    public JAXBElement<XmbCheckAvailability> createXmbCheckAvailability(XmbCheckAvailability value) {
        return new JAXBElement<XmbCheckAvailability>(_XmbCheckAvailability_QNAME, XmbCheckAvailability.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Booking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbBooking")
    public JAXBElement<Booking> createXmbBooking(Booking value) {
        return new JAXBElement<Booking>(_XmbBooking_QNAME, Booking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateLocationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateLocationResponse")
    public JAXBElement<UpdateLocationResponse> createUpdateLocationResponse(UpdateLocationResponse value) {
        return new JAXBElement<UpdateLocationResponse>(_UpdateLocationResponse_QNAME, UpdateLocationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbConfirmReservationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbConfirmReservationResponse")
    public JAXBElement<XmbConfirmReservationResponse> createXmbConfirmReservationResponse(XmbConfirmReservationResponse value) {
        return new JAXBElement<XmbConfirmReservationResponse>(_XmbConfirmReservationResponse_QNAME, XmbConfirmReservationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createBooking")
    public JAXBElement<CreateBooking> createCreateBooking(CreateBooking value) {
        return new JAXBElement<CreateBooking>(_CreateBooking_QNAME, CreateBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "openSessionResponse")
    public JAXBElement<OpenSessionResponse> createOpenSessionResponse(OpenSessionResponse value) {
        return new JAXBElement<OpenSessionResponse>(_OpenSessionResponse_QNAME, OpenSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectOrder")
    public JAXBElement<XmbSelectOrder> createXmbSelectOrder(XmbSelectOrder value) {
        return new JAXBElement<XmbSelectOrder>(_XmbSelectOrder_QNAME, XmbSelectOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateResource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateResource")
    public JAXBElement<UpdateResource> createUpdateResource(UpdateResource value) {
        return new JAXBElement<UpdateResource>(_UpdateResource_QNAME, UpdateResource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompleteOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "completeOrder")
    public JAXBElement<CompleteOrder> createCompleteOrder(CompleteOrder value) {
        return new JAXBElement<CompleteOrder>(_CompleteOrder_QNAME, CompleteOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScheduleBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "scheduleBookingResponse")
    public JAXBElement<ScheduleBookingResponse> createScheduleBookingResponse(ScheduleBookingResponse value) {
        return new JAXBElement<ScheduleBookingResponse>(_ScheduleBookingResponse_QNAME, ScheduleBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateOrderResponse")
    public JAXBElement<UpdateOrderResponse> createUpdateOrderResponse(UpdateOrderResponse value) {
        return new JAXBElement<UpdateOrderResponse>(_UpdateOrderResponse_QNAME, UpdateOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectBookingResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectBookingResponse")
    public JAXBElement<SelectBookingResponse> createSelectBookingResponse(SelectBookingResponse value) {
        return new JAXBElement<SelectBookingResponse>(_SelectBookingResponse_QNAME, SelectBookingResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCheckAvailabilityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCheckAvailabilityResponse")
    public JAXBElement<XmbCheckAvailabilityResponse> createXmbCheckAvailabilityResponse(XmbCheckAvailabilityResponse value) {
        return new JAXBElement<XmbCheckAvailabilityResponse>(_XmbCheckAvailabilityResponse_QNAME, XmbCheckAvailabilityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateLocationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateLocationResponse")
    public JAXBElement<XmbUpdateLocationResponse> createXmbUpdateLocationResponse(XmbUpdateLocationResponse value) {
        return new JAXBElement<XmbUpdateLocationResponse>(_XmbUpdateLocationResponse_QNAME, XmbUpdateLocationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbConfirmReservation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbConfirmReservation")
    public JAXBElement<XmbConfirmReservation> createXmbConfirmReservation(XmbConfirmReservation value) {
        return new JAXBElement<XmbConfirmReservation>(_XmbConfirmReservation_QNAME, XmbConfirmReservation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createOrderResponse")
    public JAXBElement<CreateOrderResponse> createCreateOrderResponse(CreateOrderResponse value) {
        return new JAXBElement<CreateOrderResponse>(_CreateOrderResponse_QNAME, CreateOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCreateOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCreateOrder")
    public JAXBElement<XmbCreateOrder> createXmbCreateOrder(XmbCreateOrder value) {
        return new JAXBElement<XmbCreateOrder>(_XmbCreateOrder_QNAME, XmbCreateOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateResourceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateResourceResponse")
    public JAXBElement<UpdateResourceResponse> createUpdateResourceResponse(UpdateResourceResponse value) {
        return new JAXBElement<UpdateResourceResponse>(_UpdateResourceResponse_QNAME, UpdateResourceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectMetaDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectMetaDataResponse")
    public JAXBElement<XmbSelectMetaDataResponse> createXmbSelectMetaDataResponse(XmbSelectMetaDataResponse value) {
        return new JAXBElement<XmbSelectMetaDataResponse>(_XmbSelectMetaDataResponse_QNAME, XmbSelectMetaDataResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailablePeriod }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbAvailablePeriod")
    public JAXBElement<AvailablePeriod> createXmbAvailablePeriod(AvailablePeriod value) {
        return new JAXBElement<AvailablePeriod>(_XmbAvailablePeriod_QNAME, AvailablePeriod.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBookingCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateBookingCodeResponse")
    public JAXBElement<UpdateBookingCodeResponse> createUpdateBookingCodeResponse(UpdateBookingCodeResponse value) {
        return new JAXBElement<UpdateBookingCodeResponse>(_UpdateBookingCodeResponse_QNAME, UpdateBookingCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectBooking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectBooking")
    public JAXBElement<SelectBooking> createSelectBooking(SelectBooking value) {
        return new JAXBElement<SelectBooking>(_SelectBooking_QNAME, SelectBooking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbLocationLine")
    public JAXBElement<LocationLine> createXmbLocationLine(LocationLine value) {
        return new JAXBElement<LocationLine>(_XmbLocationLine_QNAME, LocationLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbCloseSessionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbCloseSessionResponse")
    public JAXBElement<XmbCloseSessionResponse> createXmbCloseSessionResponse(XmbCloseSessionResponse value) {
        return new JAXBElement<XmbCloseSessionResponse>(_XmbCloseSessionResponse_QNAME, XmbCloseSessionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbUpdateResourceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbUpdateResourceResponse")
    public JAXBElement<XmbUpdateResourceResponse> createXmbUpdateResourceResponse(XmbUpdateResourceResponse value) {
        return new JAXBElement<XmbUpdateResourceResponse>(_XmbUpdateResourceResponse_QNAME, XmbUpdateResourceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "createOrder")
    public JAXBElement<CreateOrder> createCreateOrder(CreateOrder value) {
        return new JAXBElement<CreateOrder>(_CreateOrder_QNAME, CreateOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbDeleteOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbDeleteOrder")
    public JAXBElement<XmbDeleteOrder> createXmbDeleteOrder(XmbDeleteOrder value) {
        return new JAXBElement<XmbDeleteOrder>(_XmbDeleteOrder_QNAME, XmbDeleteOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmbSelectOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSelectOrderResponse")
    public JAXBElement<XmbSelectOrderResponse> createXmbSelectOrderResponse(XmbSelectOrderResponse value) {
        return new JAXBElement<XmbSelectOrderResponse>(_XmbSelectOrderResponse_QNAME, XmbSelectOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBookingCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "updateBookingCode")
    public JAXBElement<UpdateBookingCode> createUpdateBookingCode(UpdateBookingCode value) {
        return new JAXBElement<UpdateBookingCode>(_UpdateBookingCode_QNAME, UpdateBookingCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlotInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbSlotInfo")
    public JAXBElement<SlotInfo> createXmbSlotInfo(SlotInfo value) {
        return new JAXBElement<SlotInfo>(_XmbSlotInfo_QNAME, SlotInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectOrderResponse")
    public JAXBElement<SelectOrderResponse> createSelectOrderResponse(SelectOrderResponse value) {
        return new JAXBElement<SelectOrderResponse>(_SelectOrderResponse_QNAME, SelectOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetScheduleResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "getScheduleResponse")
    public JAXBElement<GetScheduleResponse> createGetScheduleResponse(GetScheduleResponse value) {
        return new JAXBElement<GetScheduleResponse>(_GetScheduleResponse_QNAME, GetScheduleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SelectMetaData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "selectMetaData")
    public JAXBElement<SelectMetaData> createSelectMetaData(SelectMetaData value) {
        return new JAXBElement<SelectMetaData>(_SelectMetaData_QNAME, SelectMetaData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvailableDay }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", name = "XmbAvailableDay")
    public JAXBElement<AvailableDay> createXmbAvailableDay(AvailableDay value) {
        return new JAXBElement<AvailableDay>(_XmbAvailableDay_QNAME, AvailableDay.class, null, value);
    }

}
