
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectResource" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbSelectResource" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectResource", propOrder = {
    "selectResource"
})
public class SelectResource {

    protected XmbSelectResource selectResource;

    /**
     * Gets the value of the selectResource property.
     * 
     * @return
     *     possible object is
     *     {@link XmbSelectResource }
     *     
     */
    public XmbSelectResource getSelectResource() {
        return selectResource;
    }

    /**
     * Sets the value of the selectResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbSelectResource }
     *     
     */
    public void setSelectResource(XmbSelectResource value) {
        this.selectResource = value;
    }

}
