
package uk.gov.ons.ctp.response.kirona.drs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAP", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAP {


    /**
     * 
     * @param updateResource
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbUpdateResourceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateResource", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateResource")
    @ResponseWrapper(localName = "updateResourceResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateResourceResponse")
    public XmbUpdateResourceResponse updateResource(
        @WebParam(name = "updateResource", targetNamespace = "")
        XmbUpdateResource updateResource);

    /**
     * 
     * @param updateBooking
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbUpdateBookingResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateBooking")
    @ResponseWrapper(localName = "updateBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateBookingResponse")
    public XmbUpdateBookingResponse updateBooking(
        @WebParam(name = "updateBooking", targetNamespace = "")
        XmbUpdateBooking updateBooking);

    /**
     * 
     * @param deleteOrder
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbDeleteOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.DeleteOrder")
    @ResponseWrapper(localName = "deleteOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.DeleteOrderResponse")
    public XmbDeleteOrderResponse deleteOrder(
        @WebParam(name = "deleteOrder", targetNamespace = "")
        XmbDeleteOrder deleteOrder);

    /**
     * 
     * @param updateBookingCode
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbUpdateBookingCodeResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBookingCode", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateBookingCode")
    @ResponseWrapper(localName = "updateBookingCodeResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateBookingCodeResponse")
    public XmbUpdateBookingCodeResponse updateBookingCode(
        @WebParam(name = "updateBookingCode", targetNamespace = "")
        XmbUpdateBookingCode updateBookingCode);

    /**
     * 
     * @param selectAlerts
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbSelectAlertsResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectAlerts", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectAlerts")
    @ResponseWrapper(localName = "selectAlertsResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectAlertsResponse")
    public XmbSelectAlertsResponse selectAlerts(
        @WebParam(name = "selectAlerts", targetNamespace = "")
        XmbSelectAlerts selectAlerts);

    /**
     * 
     * @param completeOrder
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCompleteOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "completeOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CompleteOrder")
    @ResponseWrapper(localName = "completeOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CompleteOrderResponse")
    public XmbCompleteOrderResponse completeOrder(
        @WebParam(name = "completeOrder", targetNamespace = "")
        XmbCompleteOrder completeOrder);

    /**
     * 
     * @param selectResource
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbSelectResourceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectResource", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectResource")
    @ResponseWrapper(localName = "selectResourceResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectResourceResponse")
    public XmbSelectResourceResponse selectResource(
        @WebParam(name = "selectResource", targetNamespace = "")
        XmbSelectResource selectResource);

    /**
     * 
     * @param selectMetaData
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbSelectMetaDataResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectMetaData", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectMetaData")
    @ResponseWrapper(localName = "selectMetaDataResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectMetaDataResponse")
    public XmbSelectMetaDataResponse selectMetaData(
        @WebParam(name = "selectMetaData", targetNamespace = "")
        XmbSelectMetaData selectMetaData);

    /**
     * 
     * @param createReservation
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCreateReservationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createReservation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateReservation")
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateReservationResponse")
    public XmbCreateReservationResponse createReservation(
        @WebParam(name = "createReservation", targetNamespace = "")
        XmbCreateReservation createReservation);

    /**
     * 
     * @param deleteBooking
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbDeleteBookingResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.DeleteBooking")
    @ResponseWrapper(localName = "deleteBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.DeleteBookingResponse")
    public XmbDeleteBookingResponse deleteBooking(
        @WebParam(name = "deleteBooking", targetNamespace = "")
        XmbDeleteBooking deleteBooking);

    /**
     * 
     * @param updateLocation
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbUpdateLocationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLocation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateLocation")
    @ResponseWrapper(localName = "updateLocationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateLocationResponse")
    public XmbUpdateLocationResponse updateLocation(
        @WebParam(name = "updateLocation", targetNamespace = "")
        XmbUpdateLocation updateLocation);

    /**
     * 
     * @param updateOrder
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbUpdateOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateOrder")
    @ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.UpdateOrderResponse")
    public XmbUpdateOrderResponse updateOrder(
        @WebParam(name = "updateOrder", targetNamespace = "")
        XmbUpdateOrder updateOrder);

    /**
     * 
     * @param confirmReservation
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbConfirmReservationResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmReservation", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.ConfirmReservation")
    @ResponseWrapper(localName = "confirmReservationResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.ConfirmReservationResponse")
    public XmbConfirmReservationResponse confirmReservation(
        @WebParam(name = "confirmReservation", targetNamespace = "")
        XmbConfirmReservation confirmReservation);

    /**
     * 
     * @param createOrder
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCreateOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateOrderResponse")
    public XmbCreateOrderResponse createOrder(
        @WebParam(name = "createOrder", targetNamespace = "")
        XmbCreateOrder createOrder);

    /**
     * 
     * @param scheduleBooking
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbScheduleBookingResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scheduleBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.ScheduleBooking")
    @ResponseWrapper(localName = "scheduleBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.ScheduleBookingResponse")
    public XmbScheduleBookingResponse scheduleBooking(
        @WebParam(name = "scheduleBooking", targetNamespace = "")
        XmbScheduleBooking scheduleBooking);

    /**
     * 
     * @param selectOrder
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbSelectOrderResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectOrder", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectOrder")
    @ResponseWrapper(localName = "selectOrderResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectOrderResponse")
    public XmbSelectOrderResponse selectOrder(
        @WebParam(name = "selectOrder", targetNamespace = "")
        XmbSelectOrder selectOrder);

    /**
     * 
     * @param closeSession
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCloseSessionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeSession", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CloseSession")
    @ResponseWrapper(localName = "closeSessionResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CloseSessionResponse")
    public XmbCloseSessionResponse closeSession(
        @WebParam(name = "closeSession", targetNamespace = "")
        XmbCloseSession closeSession);

    /**
     * 
     * @param getSchedule
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbGetScheduleResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSchedule", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.GetSchedule")
    @ResponseWrapper(localName = "getScheduleResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.GetScheduleResponse")
    public XmbGetScheduleResponse getSchedule(
        @WebParam(name = "getSchedule", targetNamespace = "")
        XmbGetSchedule getSchedule);

    /**
     * 
     * @param createBooking
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCreateBookingResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateBooking")
    @ResponseWrapper(localName = "createBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CreateBookingResponse")
    public XmbCreateBookingResponse createBooking(
        @WebParam(name = "createBooking", targetNamespace = "")
        XmbCreateBooking createBooking);

    /**
     * 
     * @param openSession
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbOpenSessionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openSession", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.OpenSession")
    @ResponseWrapper(localName = "openSessionResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.OpenSessionResponse")
    public XmbOpenSessionResponse openSession(
        @WebParam(name = "openSession", targetNamespace = "")
        XmbOpenSession openSession);

    /**
     * 
     * @param checkAvailability
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbCheckAvailabilityResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkAvailability", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CheckAvailability")
    @ResponseWrapper(localName = "checkAvailabilityResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.CheckAvailabilityResponse")
    public XmbCheckAvailabilityResponse checkAvailability(
        @WebParam(name = "checkAvailability", targetNamespace = "")
        XmbCheckAvailability checkAvailability);

    /**
     * 
     * @param selectBooking
     * @return
     *     returns uk.gov.ons.ctp.response.kirona.drs.XmbSelectBookingResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectBooking", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectBooking")
    @ResponseWrapper(localName = "selectBookingResponse", targetNamespace = "http://autogenerated.OTWebServiceApi.xmbrace.com/", className = "uk.gov.ons.ctp.response.kirona.drs.SelectBookingResponse")
    public XmbSelectBookingResponse selectBooking(
        @WebParam(name = "selectBooking", targetNamespace = "")
        XmbSelectBooking selectBooking);

}
