package uk.gov.ons.ctp.response.kirona.drs;

import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.*;

/**
 * This is a basic client to verify that we can implement the Create Vit Job sequence described at
 * http://192.168.10.11/Kirona_DRS_Integration_Design#Create_Visit_Job
 */
public class TestClient {
  /**
   * The main
   * @param args the main params
   */
  public static void main(final String[] args) {
    SOAP_Service soapService = new SOAP_Service();
    SOAP soap = soapService.getSOAPImplPort();

    System.out.println("Obtaining a sesssion...");
    XmbOpenSession session = new XmbOpenSession();
    session.setLogin("login");
    session.setPassword("password");
    XmbOpenSessionResponse sessionResponse = soap.openSession(session);
    String sessionId = sessionResponse.getSessionId();
    System.out.println("Obtained a session with id " + sessionId);

    XmbCreateOrder order = new XmbCreateOrder();
    order.setSessionId(sessionId);
    Order anOrder = new Order();
    anOrder.setContactName("Joe Blogg");
    anOrder.setPhone("02380112233");
    order.setTheOrder(anOrder);
    XmbCreateOrderResponse orderResponse = soap.createOrder(order);
    System.out.println("Created an order. Response is " + orderResponse);

    // TODO Schedule bookings
    XmbCloseSession closingSession = new XmbCloseSession();
    closingSession.setSessionId(sessionId);
    XmbCloseSessionResponse closingSessionResponse = soap.closeSession(closingSession);
    System.out.println("Closed session. Response was = " + closingSessionResponse);
  }
}
