package uk.gov.ons.ctp.response.kirona.drs;

import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.*;

import java.util.List;

/**
 * This is a basic client to verify that we can implement the Create Vit Job sequence described at
 * http://192.168.10.11/Kirona_DRS_Integration_Design#Create_Visit_Job
 */
public class TestClient {
  /**
   * The main
   * @param args the main params
   */
  public static void main(final String[] args) {
    SOAP_Service soapService = new SOAP_Service();
    SOAP soap = soapService.getSOAPImplPort();

    System.out.println("Obtaining a sesssion...");
    XmbOpenSession session = new XmbOpenSession();
    // TODO which credentials shall we use?
    session.setLogin("login");
    session.setPassword("password");
    XmbOpenSessionResponse sessionResponse = soap.openSession(session);
    String sessionId = sessionResponse.getSessionId();
    System.out.println("Obtained a session with id " + sessionId);

    XmbCreateOrder order = new XmbCreateOrder();
    order.setSessionId(sessionId);
    Order anOrder = new Order();
    anOrder.setContactName("Joe Blogg");
    anOrder.setPhone("02380112233");
    order.setTheOrder(anOrder);
    XmbCreateOrderResponse orderResponse = soap.createOrder(order);
    System.out.println("Created an order. Response is " + orderResponse);

    Order responseForAnOrder = orderResponse.getTheOrder();
    List<Booking> bookingList = responseForAnOrder.getTheBookings();
    for (Booking aBooking : bookingList) {
      XmbScheduleBooking scheduleBooking = new XmbScheduleBooking();
      scheduleBooking.setSessionId(sessionId);
      scheduleBooking.setUserId("userId");
      scheduleBooking.setTheBooking(aBooking);
      XmbScheduleBookingResponse scheduleBookingResponse = soap.scheduleBooking(scheduleBooking);
      ResponseStatus status = scheduleBookingResponse.getStatus();
      String statusValue = status.value();
      System.out.println("Scheduled a booking and associated response has for status = " + statusValue);
    }

    XmbCloseSession closingSession = new XmbCloseSession();
    closingSession.setSessionId(sessionId);
    XmbCloseSessionResponse closingSessionResponse = soap.closeSession(closingSession);
    System.out.println("Closed session. Response was = " + closingSessionResponse);
  }
}
