
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateLocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateLocation" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbUpdateLocation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateLocation", propOrder = {
    "updateLocation"
})
public class UpdateLocation {

    protected XmbUpdateLocation updateLocation;

    /**
     * Gets the value of the updateLocation property.
     * 
     * @return
     *     possible object is
     *     {@link XmbUpdateLocation }
     *     
     */
    public XmbUpdateLocation getUpdateLocation() {
        return updateLocation;
    }

    /**
     * Sets the value of the updateLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbUpdateLocation }
     *     
     */
    public void setUpdateLocation(XmbUpdateLocation value) {
        this.updateLocation = value;
    }

}
