
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateBooking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateBooking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbUpdateBooking" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateBooking", propOrder = {
    "updateBooking"
})
public class UpdateBooking {

    protected XmbUpdateBooking updateBooking;

    /**
     * Gets the value of the updateBooking property.
     * 
     * @return
     *     possible object is
     *     {@link XmbUpdateBooking }
     *     
     */
    public XmbUpdateBooking getUpdateBooking() {
        return updateBooking;
    }

    /**
     * Sets the value of the updateBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbUpdateBooking }
     *     
     */
    public void setUpdateBooking(XmbUpdateBooking value) {
        this.updateBooking = value;
    }

}
