
package uk.gov.ons.ctp.response.kirona.drs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateResource">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateResource" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbUpdateResource" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateResource", propOrder = {
    "updateResource"
})
public class UpdateResource {

    protected XmbUpdateResource updateResource;

    /**
     * Gets the value of the updateResource property.
     * 
     * @return
     *     possible object is
     *     {@link XmbUpdateResource }
     *     
     */
    public XmbUpdateResource getUpdateResource() {
        return updateResource;
    }

    /**
     * Sets the value of the updateResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbUpdateResource }
     *     
     */
    public void setUpdateResource(XmbUpdateResource value) {
        this.updateResource = value;
    }

}
