
package uk.gov.ons.ctp.response.kirona.drs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmbSelectMetaDataResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmbSelectMetaDataResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}commandResponse">
 *       &lt;sequence>
 *         &lt;element name="theBusinessDataDefinitions" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}businessDataDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theResourceTemplates" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}resourceTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theUnavailabilityReasons" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}unavailabilityReason" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmbSelectMetaDataResponse", propOrder = {
    "theBusinessDataDefinitions",
    "theResourceTemplates",
    "theUnavailabilityReasons"
})
public class XmbSelectMetaDataResponse
    extends CommandResponse
{

    protected List<BusinessDataDefinition> theBusinessDataDefinitions;
    protected List<ResourceTemplate> theResourceTemplates;
    protected List<UnavailabilityReason> theUnavailabilityReasons;

    /**
     * Gets the value of the theBusinessDataDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theBusinessDataDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheBusinessDataDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessDataDefinition }
     * 
     * 
     */
    public List<BusinessDataDefinition> getTheBusinessDataDefinitions() {
        if (theBusinessDataDefinitions == null) {
            theBusinessDataDefinitions = new ArrayList<BusinessDataDefinition>();
        }
        return this.theBusinessDataDefinitions;
    }

    /**
     * Gets the value of the theResourceTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theResourceTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheResourceTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceTemplate }
     * 
     * 
     */
    public List<ResourceTemplate> getTheResourceTemplates() {
        if (theResourceTemplates == null) {
            theResourceTemplates = new ArrayList<ResourceTemplate>();
        }
        return this.theResourceTemplates;
    }

    /**
     * Gets the value of the theUnavailabilityReasons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theUnavailabilityReasons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheUnavailabilityReasons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnavailabilityReason }
     * 
     * 
     */
    public List<UnavailabilityReason> getTheUnavailabilityReasons() {
        if (theUnavailabilityReasons == null) {
            theUnavailabilityReasons = new ArrayList<UnavailabilityReason>();
        }
        return this.theUnavailabilityReasons;
    }

}
