INSERT INTO casesvc.category (categorypk, shortdescription, longdescription, eventtype, role, generatedactiontype, "group", oldcasesampleunittypes, newcasesampleunittype, recalccollectioninstrument)
VALUES ('PRIVACY_DATA_CONFIDENTIALITY_CONCERNS', '411', 'Privacy/Data Security/Confidentiality concerns', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('LEGITIMACY_CONCERNS', '412', 'Legitimacy concerns', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('OTHER_OUTRIGHT_REFUSAL', '413', 'Other outright refusal', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('ILL_AT_HOME', '511', 'Ill at home during survey period', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('IN_HOSPITAL', '521', 'Away/In hospital throughout field period', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('PHYSICALLY_OR_MENTALLY_UNABLE', '531', 'Physically or mentally unable/incompetent', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('LANGUAGE_DIFFICULTIES', '541', 'Language difficulties', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('FULL_INTERVIEW_REQUEST_DATA_DELETED', '561', 'Full interview achieved but respondent requested data be deleted', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('PARTIAL_INTERVIEW_REQUEST_DATA_DELETED', '562', 'Partial interview achieved but respondent requested data be deleted', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('FULL_INTERVIEW_REQUEST_DATA_DELETED_INCORRECT', '563', 'Full interview achieved but respondent requested data be deleted as it is incorrect', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('PARTIAL_INTERVIEW_REQUEST_DATA_DELETED_INCORRECT', '564', 'Partial interview achieved but respondent requested data be deleted as it is incorrect', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('LACK_OF_COMPUTER_INTERNET_ACCESS', '571', 'Lack of computer or internet access', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('TOO_BUSY', '572', 'Too Busy', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('OTHER_CIRCUMSTANTIAL_REFUSAL', '573', 'Other circumstantial refusal (Further detail to be provided in the notes field)', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('COMPLY_IN_DIFFERENT_COLLECTION_MODE', '581', 'Willing to comply in a different collection mode', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('REQUEST_TO_COMPLETE_IN_ALTERNATIVE_FORMAT', '582', 'Request to complete in an alternative format which is not currently available', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('NO_TRACE_OF_ADDRESS', '632', 'No trace of address: returned mail to Head Office', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('WRONG_ADDRESS', '633', 'Wrong Address', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('VACANT_OR_EMPTY', '730', 'Vacant/empty', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('NON_RESIDENTIAL_ADDRESS', '740', 'Non-residential address', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('ADDRESS_OCCUPIED_NO_RESIDENT', '750', 'Address occupied, but no resident household/resident(s)', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('COMMUNAL_ESTABLISHMENT_INSTITUTION', '760', 'Communal establishment/institution', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('DWELLING_OF_FOREIGN_SERVICE_PERSONNEL_DIPLOMATS', '771', 'Dwelling of foreign service personnel/diplomats', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('NO_PERSON_IN_ELIGIBLE_AGE_RANGE', '772', 'No person in eligible age range', NULL,  NULL, NULL, NULL, 'H', NULL, NULL),
 ('DECEASED', '792', 'Deceased', NULL,  NULL, NULL, NULL, 'H', NULL, NULL);