package uk.gov.ons.ctp.response;

import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.SOAP;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.SOAP_Service;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.XmbCreateOrder;
import uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode.XmbCreateOrderResponse;

/**
 * This is a basic client to verify that we can create an order on the Kirona's side
 */
public class TestClient {
  /**
   * The main
   * @param args the main params
   */
  public static void main(final String[] args) {
    SOAP_Service soapService = new SOAP_Service();
    SOAP soap = soapService.getSOAPImplPort();
    XmbCreateOrder order = new XmbCreateOrder();
    XmbCreateOrderResponse response = soap.createOrder(order);
    System.out.println("response = " + response);
  }
}
