
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for completeOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="completeOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="completeOrder" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbCompleteOrder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "completeOrder", propOrder = {
    "completeOrder"
})
public class CompleteOrder {

    protected XmbCompleteOrder completeOrder;

    /**
     * Gets the value of the completeOrder property.
     * 
     * @return
     *     possible object is
     *     {@link XmbCompleteOrder }
     *     
     */
    public XmbCompleteOrder getCompleteOrder() {
        return completeOrder;
    }

    /**
     * Sets the value of the completeOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbCompleteOrder }
     *     
     */
    public void setCompleteOrder(XmbCompleteOrder value) {
        this.completeOrder = value;
    }

}
