
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createBooking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createBooking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbCreateBooking" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createBooking", propOrder = {
    "createBooking"
})
public class CreateBooking {

    protected XmbCreateBooking createBooking;

    /**
     * Gets the value of the createBooking property.
     * 
     * @return
     *     possible object is
     *     {@link XmbCreateBooking }
     *     
     */
    public XmbCreateBooking getCreateBooking() {
        return createBooking;
    }

    /**
     * Sets the value of the createBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbCreateBooking }
     *     
     */
    public void setCreateBooking(XmbCreateBooking value) {
        this.createBooking = value;
    }

}
