
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for daySlotsInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="daySlotsInfo">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}entity">
 *       &lt;sequence>
 *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="nonWorkingDay" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="slotsForDay" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}slotInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="weeklyDayOff" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "daySlotsInfo", propOrder = {
    "day",
    "nonWorkingDay",
    "slotsForDay",
    "weeklyDayOff"
})
public class DaySlotsInfo
    extends Entity
{

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar day;
    @XmlElement(defaultValue = "false")
    protected boolean nonWorkingDay;
    protected List<SlotInfo> slotsForDay;
    @XmlElement(defaultValue = "false")
    protected boolean weeklyDayOff;

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDay(XMLGregorianCalendar value) {
        this.day = value;
    }

    /**
     * Gets the value of the nonWorkingDay property.
     * 
     */
    public boolean isNonWorkingDay() {
        return nonWorkingDay;
    }

    /**
     * Sets the value of the nonWorkingDay property.
     * 
     */
    public void setNonWorkingDay(boolean value) {
        this.nonWorkingDay = value;
    }

    /**
     * Gets the value of the slotsForDay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the slotsForDay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSlotsForDay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SlotInfo }
     * 
     * 
     */
    public List<SlotInfo> getSlotsForDay() {
        if (slotsForDay == null) {
            slotsForDay = new ArrayList<SlotInfo>();
        }
        return this.slotsForDay;
    }

    /**
     * Gets the value of the weeklyDayOff property.
     * 
     */
    public boolean isWeeklyDayOff() {
        return weeklyDayOff;
    }

    /**
     * Sets the value of the weeklyDayOff property.
     * 
     */
    public void setWeeklyDayOff(boolean value) {
        this.weeklyDayOff = value;
    }

}
