
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getSchedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getSchedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="getSchedule" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbGetSchedule" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getSchedule", propOrder = {
    "getSchedule"
})
public class GetSchedule {

    protected XmbGetSchedule getSchedule;

    /**
     * Gets the value of the getSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link XmbGetSchedule }
     *     
     */
    public XmbGetSchedule getGetSchedule() {
        return getSchedule;
    }

    /**
     * Sets the value of the getSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbGetSchedule }
     *     
     */
    public void setGetSchedule(XmbGetSchedule value) {
        this.getSchedule = value;
    }

}
