
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for openSession complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="openSession">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="openSession" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbOpenSession" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "openSession", propOrder = {
    "openSession"
})
public class OpenSession {

    protected XmbOpenSession openSession;

    /**
     * Gets the value of the openSession property.
     * 
     * @return
     *     possible object is
     *     {@link XmbOpenSession }
     *     
     */
    public XmbOpenSession getOpenSession() {
        return openSession;
    }

    /**
     * Sets the value of the openSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbOpenSession }
     *     
     */
    public void setOpenSession(XmbOpenSession value) {
        this.openSession = value;
    }

}
