
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scheduleBooking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scheduleBooking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduleBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbScheduleBooking" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scheduleBooking", propOrder = {
    "scheduleBooking"
})
public class ScheduleBooking {

    protected XmbScheduleBooking scheduleBooking;

    /**
     * Gets the value of the scheduleBooking property.
     * 
     * @return
     *     possible object is
     *     {@link XmbScheduleBooking }
     *     
     */
    public XmbScheduleBooking getScheduleBooking() {
        return scheduleBooking;
    }

    /**
     * Sets the value of the scheduleBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbScheduleBooking }
     *     
     */
    public void setScheduleBooking(XmbScheduleBooking value) {
        this.scheduleBooking = value;
    }

}
