
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectOrder" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbSelectOrder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectOrder", propOrder = {
    "selectOrder"
})
public class SelectOrder {

    protected XmbSelectOrder selectOrder;

    /**
     * Gets the value of the selectOrder property.
     * 
     * @return
     *     possible object is
     *     {@link XmbSelectOrder }
     *     
     */
    public XmbSelectOrder getSelectOrder() {
        return selectOrder;
    }

    /**
     * Sets the value of the selectOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbSelectOrder }
     *     
     */
    public void setSelectOrder(XmbSelectOrder value) {
        this.selectOrder = value;
    }

}
