
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selectMetaData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectMetaData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="selectMetaData" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbSelectMetaData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectMetaData", propOrder = {
    "selectMetaData"
})
public class SelectMetaData {

    protected XmbSelectMetaData selectMetaData;

    /**
     * Gets the value of the selectMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link XmbSelectMetaData }
     *     
     */
    public XmbSelectMetaData getSelectMetaData() {
        return selectMetaData;
    }

    /**
     * Sets the value of the selectMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbSelectMetaData }
     *     
     */
    public void setSelectMetaData(XmbSelectMetaData value) {
        this.selectMetaData = value;
    }

}
