
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateBookingCode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateBookingCode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateBookingCode" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbUpdateBookingCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateBookingCode", propOrder = {
    "updateBookingCode"
})
public class UpdateBookingCode {

    protected XmbUpdateBookingCode updateBookingCode;

    /**
     * Gets the value of the updateBookingCode property.
     * 
     * @return
     *     possible object is
     *     {@link XmbUpdateBookingCode }
     *     
     */
    public XmbUpdateBookingCode getUpdateBookingCode() {
        return updateBookingCode;
    }

    /**
     * Sets the value of the updateBookingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbUpdateBookingCode }
     *     
     */
    public void setUpdateBookingCode(XmbUpdateBookingCode value) {
        this.updateBookingCode = value;
    }

}
