
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for updateOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="updateOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="updateOrder" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}xmbUpdateOrder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateOrder", propOrder = {
    "updateOrder"
})
public class UpdateOrder {

    protected XmbUpdateOrder updateOrder;

    /**
     * Gets the value of the updateOrder property.
     * 
     * @return
     *     possible object is
     *     {@link XmbUpdateOrder }
     *     
     */
    public XmbUpdateOrder getUpdateOrder() {
        return updateOrder;
    }

    /**
     * Sets the value of the updateOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmbUpdateOrder }
     *     
     */
    public void setUpdateOrder(XmbUpdateOrder value) {
        this.updateOrder = value;
    }

}
