
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmbDeleteBookingResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmbDeleteBookingResponse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}commandResponse">
 *       &lt;sequence>
 *         &lt;element name="theBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}booking" minOccurs="0"/>
 *         &lt;element name="theOrder" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}order" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmbDeleteBookingResponse", propOrder = {
    "theBooking",
    "theOrder"
})
public class XmbDeleteBookingResponse
    extends CommandResponse
{

    protected Booking theBooking;
    protected Order theOrder;

    /**
     * Gets the value of the theBooking property.
     * 
     * @return
     *     possible object is
     *     {@link Booking }
     *     
     */
    public Booking getTheBooking() {
        return theBooking;
    }

    /**
     * Sets the value of the theBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Booking }
     *     
     */
    public void setTheBooking(Booking value) {
        this.theBooking = value;
    }

    /**
     * Gets the value of the theOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Order }
     *     
     */
    public Order getTheOrder() {
        return theOrder;
    }

    /**
     * Sets the value of the theOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Order }
     *     
     */
    public void setTheOrder(Order value) {
        this.theOrder = value;
    }

}
