
package uk.gov.ons.ctp.response.kirona.drs.autogeneratedcode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for xmbUpdateBooking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmbUpdateBooking">
 *   &lt;complexContent>
 *     &lt;extension base="{http://autogenerated.OTWebServiceApi.xmbrace.com/}command">
 *       &lt;sequence>
 *         &lt;element name="actionTaken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bookingCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="completeOrder" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="endDateAndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startDateAndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="theBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}booking"/>
 *         &lt;element name="theFollowOnBooking" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}booking" minOccurs="0"/>
 *         &lt;element name="transactionType" type="{http://autogenerated.OTWebServiceApi.xmbrace.com/}transactionTypeType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmbUpdateBooking", propOrder = {
    "actionTaken",
    "bookingCategory",
    "completeOrder",
    "endDateAndTime",
    "resourceId",
    "sessionId",
    "startDateAndTime",
    "theBooking",
    "theFollowOnBooking",
    "transactionType"
})
public class XmbUpdateBooking
    extends Command
{

    protected String actionTaken;
    protected String bookingCategory;
    protected boolean completeOrder;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateAndTime;
    @XmlElement(required = true)
    protected String resourceId;
    @XmlElement(required = true)
    protected String sessionId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDateAndTime;
    @XmlElement(required = true)
    protected Booking theBooking;
    protected Booking theFollowOnBooking;
    @XmlElement(required = true)
    protected TransactionTypeType transactionType;

    /**
     * Gets the value of the actionTaken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionTaken() {
        return actionTaken;
    }

    /**
     * Sets the value of the actionTaken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionTaken(String value) {
        this.actionTaken = value;
    }

    /**
     * Gets the value of the bookingCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingCategory() {
        return bookingCategory;
    }

    /**
     * Sets the value of the bookingCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingCategory(String value) {
        this.bookingCategory = value;
    }

    /**
     * Gets the value of the completeOrder property.
     * 
     */
    public boolean isCompleteOrder() {
        return completeOrder;
    }

    /**
     * Sets the value of the completeOrder property.
     * 
     */
    public void setCompleteOrder(boolean value) {
        this.completeOrder = value;
    }

    /**
     * Gets the value of the endDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateAndTime() {
        return endDateAndTime;
    }

    /**
     * Sets the value of the endDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateAndTime(XMLGregorianCalendar value) {
        this.endDateAndTime = value;
    }

    /**
     * Gets the value of the resourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * Sets the value of the resourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceId(String value) {
        this.resourceId = value;
    }

    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

    /**
     * Gets the value of the startDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDateAndTime() {
        return startDateAndTime;
    }

    /**
     * Sets the value of the startDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDateAndTime(XMLGregorianCalendar value) {
        this.startDateAndTime = value;
    }

    /**
     * Gets the value of the theBooking property.
     * 
     * @return
     *     possible object is
     *     {@link Booking }
     *     
     */
    public Booking getTheBooking() {
        return theBooking;
    }

    /**
     * Sets the value of the theBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Booking }
     *     
     */
    public void setTheBooking(Booking value) {
        this.theBooking = value;
    }

    /**
     * Gets the value of the theFollowOnBooking property.
     * 
     * @return
     *     possible object is
     *     {@link Booking }
     *     
     */
    public Booking getTheFollowOnBooking() {
        return theFollowOnBooking;
    }

    /**
     * Sets the value of the theFollowOnBooking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Booking }
     *     
     */
    public void setTheFollowOnBooking(Booking value) {
        this.theFollowOnBooking = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionTypeType }
     *     
     */
    public TransactionTypeType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionTypeType }
     *     
     */
    public void setTransactionType(TransactionTypeType value) {
        this.transactionType = value;
    }

}
