@startuml
skinparam state {
    BackgroundColor HoneyDew
}

[*] --> NOTSTARTED
NOTSTARTED --> INPROGRESS : collection_instrument_downloaded
NOTSTARTED --> INPROGRESS : EQ_LAUNCH
NOTSTARTED --> COMPLETE : successful_response_upload
NOTSTARTED --> NOTSTARTED: ACCESS_CODE_AUTHENTICATION_ATTEMPT

NOTSTARTED --> COMPLETEDBYPHONE : completed_by_phone
NOTSTARTED --> NOLONGERREQUIRED : no_longer_required
    
INPROGRESS --> COMPLETE : offline_response_processed
INPROGRESS --> COMPLETE : successful_response_upload
INPROGRESS -> INPROGRESS: EQ_LAUNCH
INPROGRESS -> INPROGRESS: ACCESS_CODE_AUTHENTICATION_ATTEMPT
INPROGRESS -> COMPLETEDBYPHONE : completed_by_phone
INPROGRESS --> NOLONGERREQUIRED : no_longer_required

REOPENED --> COMPLETEDBYPHONE : completed_by_phone
REOPENED --> NOLONGERREQUIRED : no_longer_required
@enduml