//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 05:48:38 PM BST
//

package uk.gov.ons.ctp.response.lib.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Java class for CaseReceipt complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CaseReceipt">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caseRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inboundChannel" type="{http://ons.gov.uk/ctp/response/casesvc/message/feedback}InboundChannel"/>
 *         &lt;element name="responseDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "CaseReceipt",
    namespace = "http://ons.gov.uk/ctp/response/casesvc/message/feedback",
    propOrder = {"caseRef", "caseId", "inboundChannel", "responseDateTime", "partyId"})
public class CaseReceipt {

  protected String caseRef;

  @XmlElement(required = true)
  protected String caseId;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected InboundChannel inboundChannel;

  @XmlElement(required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar responseDateTime;

  protected String partyId;

  /**
   * Gets the value of the caseRef property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseRef() {
    return caseRef;
  }

  /**
   * Sets the value of the caseRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseRef(String value) {
    this.caseRef = value;
  }

  /**
   * Gets the value of the caseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseId() {
    return caseId;
  }

  /**
   * Sets the value of the caseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseId(String value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the inboundChannel property.
   *
   * @return possible object is {@link InboundChannel }
   */
  public InboundChannel getInboundChannel() {
    return inboundChannel;
  }

  /**
   * Sets the value of the inboundChannel property.
   *
   * @param value allowed object is {@link InboundChannel }
   */
  public void setInboundChannel(InboundChannel value) {
    this.inboundChannel = value;
  }

  /**
   * Gets the value of the responseDateTime property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getResponseDateTime() {
    return responseDateTime;
  }

  /**
   * Sets the value of the responseDateTime property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setResponseDateTime(XMLGregorianCalendar value) {
    this.responseDateTime = value;
  }

  /**
   * Gets the value of the partyId property.
   *
   * @return possible object is {@link String }
   */
  public String getPartyId() {
    return partyId;
  }

  /**
   * Sets the value of the partyId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPartyId(String value) {
    this.partyId = value;
  }
}
