//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 05:50:31 PM BST
//

package uk.gov.ons.ctp.response.lib.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for CaseNotification complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CaseNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="sampleUnitId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="actionPlanId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="exerciseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sampleUnitType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notificationType" type="{http://ons.gov.uk/ctp/response/casesvc/message/notification}NotificationType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "CaseNotification",
    propOrder = {})
public class CaseNotification {

  protected String sampleUnitId;

  @XmlElement(required = true)
  protected String caseId;

  @XmlElement(required = true)
  protected String actionPlanId;

  @XmlElement(required = true)
  protected String exerciseId;

  protected String partyId;
  protected String sampleUnitType;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected NotificationType notificationType;

  /**
   * Gets the value of the sampleUnitId property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUnitId() {
    return sampleUnitId;
  }

  /**
   * Sets the value of the sampleUnitId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUnitId(String value) {
    this.sampleUnitId = value;
  }

  /**
   * Gets the value of the caseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseId() {
    return caseId;
  }

  /**
   * Sets the value of the caseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseId(String value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the actionPlanId property.
   *
   * @return possible object is {@link String }
   */
  public String getActionPlanId() {
    return actionPlanId;
  }

  /**
   * Sets the value of the actionPlanId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActionPlanId(String value) {
    this.actionPlanId = value;
  }

  /**
   * Gets the value of the exerciseId property.
   *
   * @return possible object is {@link String }
   */
  public String getExerciseId() {
    return exerciseId;
  }

  /**
   * Sets the value of the exerciseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setExerciseId(String value) {
    this.exerciseId = value;
  }

  /**
   * Gets the value of the partyId property.
   *
   * @return possible object is {@link String }
   */
  public String getPartyId() {
    return partyId;
  }

  /**
   * Sets the value of the partyId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPartyId(String value) {
    this.partyId = value;
  }

  /**
   * Gets the value of the sampleUnitType property.
   *
   * @return possible object is {@link String }
   */
  public String getSampleUnitType() {
    return sampleUnitType;
  }

  /**
   * Sets the value of the sampleUnitType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSampleUnitType(String value) {
    this.sampleUnitType = value;
  }

  /**
   * Gets the value of the notificationType property.
   *
   * @return possible object is {@link NotificationType }
   */
  public NotificationType getNotificationType() {
    return notificationType;
  }

  /**
   * Sets the value of the notificationType property.
   *
   * @param value allowed object is {@link NotificationType }
   */
  public void setNotificationType(NotificationType value) {
    this.notificationType = value;
  }
}
