//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 05:50:31 PM BST
//

package uk.gov.ons.ctp.response.lib.message;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for NotificationType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="NotificationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACTIVATED"/>
 *     &lt;enumeration value="REPLACED"/>
 *     &lt;enumeration value="DEACTIVATED"/>
 *     &lt;enumeration value="DISABLED"/>
 *     &lt;enumeration value="ACTIONPLAN_CHANGED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "NotificationType")
@XmlEnum
public enum NotificationType {
  ACTIVATED,
  REPLACED,
  DEACTIVATED,
  DISABLED,
  ACTIONPLAN_CHANGED;

  public String value() {
    return name();
  }

  public static NotificationType fromValue(String v) {
    return valueOf(v);
  }
}
