//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.30 at 05:50:31 PM BST
//

package uk.gov.ons.ctp.response.lib.message;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the uk.gov.ons.ctp.response.lib.message package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private static final QName _CaseNotification_QNAME =
      new QName("http://ons.gov.uk/ctp/response/casesvc/message/notification", "caseNotification");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: uk.gov.ons.ctp.response.lib.message
   */
  public ObjectFactory() {}

  /** Create an instance of {@link CaseNotification } */
  public CaseNotification createCaseNotification() {
    return new CaseNotification();
  }

  /** Create an instance of {@link JAXBElement }{@code <}{@link CaseNotification }{@code >}} */
  @XmlElementDecl(
      namespace = "http://ons.gov.uk/ctp/response/casesvc/message/notification",
      name = "caseNotification")
  public JAXBElement<CaseNotification> createCaseNotification(CaseNotification value) {
    return new JAXBElement<CaseNotification>(
        _CaseNotification_QNAME, CaseNotification.class, null, value);
  }
}
