set schema 'casesvc';

--casetype

INSERT INTO CASETYPE VALUES (23,'I1S','individual questionnaire with sex id england','I1S','I');
INSERT INTO CASETYPE VALUES (24,'I1','individual questionnaire no sex id england','I1','I');

--actionplanmapping
INSERT INTO ACTIONPLANMAPPING VALUES (23,17, 23, false, 'PAPER','ENGLISH','POST');
INSERT INTO ACTIONPLANMAPPING VALUES (24,19, 23, false, 'ONLINE','ENGLISH','SMS');
INSERT INTO ACTIONPLANMAPPING VALUES (25,20, 23, false, 'ONLINE','ENGLISH','EMAIL');
INSERT INTO ACTIONPLANMAPPING VALUES (26,21, 23, false, 'ONLINE','ENGLISH','LETTER');
INSERT INTO ACTIONPLANMAPPING VALUES (27,18, 24, false, 'PAPER','ENGLISH','POST');
INSERT INTO ACTIONPLANMAPPING VALUES (28,19, 24, false, 'ONLINE','ENGLISH','SMS');
INSERT INTO ACTIONPLANMAPPING VALUES (29,20, 24, false, 'ONLINE','ENGLISH','EMAIL');
INSERT INTO ACTIONPLANMAPPING VALUES (30,21, 24, false, 'ONLINE','ENGLISH','LETTER');

--samplecasetypeselector
INSERT INTO SAMPLECASETYPESELECTOR VALUES (23, 1, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (24, 2, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (25, 3, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (26, 4, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (27, 5, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (28, 6, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (29, 7, 23,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (30, 11, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (31, 9, 23,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (32, 13, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (33, 15, 23,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (34, 17, 24,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (35, 19, 23,'I');
INSERT INTO SAMPLECASETYPESELECTOR VALUES (36, 21, 24,'I');
