name: a1
on: [pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1]
        steps:
          - shell: bash
            run: |
              echo "${{ secrets.BOT_EMAIL }}"
